In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
df = pd.read_csv("01_flats.csv")

In [3]:
df.sample(3)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1428,3 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,BPTP Terra3.8 ★,1.45 Crore,"₹ 8,006/sq.ft.",Super Built up area 1811(168.25 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8th of 23 Floors,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou...",E70094582
2120,3 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Hero Homes,1.4 Crore,"₹ 15,826/sq.ft.",Super Built up area 1389(129.04 sq.m.)Carpet a...,3 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 104 Gurgaon, Gurgaon, Haryana",4th of 26 Floors,North,Dec 2023,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",4th floor property in tower 02,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5...",X61172132
2489,2 BHK Flat in Sector 36A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,AVL 36 Gurgaon3.7 ★,75 Lac,"₹ 7,500/sq.ft.",Super Built up area 1000(92.9 sq.m.)Carpet are...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 36A Gurgaon, Gurgaon, Haryana",5th of 10 Floors,North-East,1 to 5 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Sh...","This 2 bhk flat is located in avl 36 gurgaon, ...","['1 Wardrobe', '3 Fan', '6 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4.5 out of 5', 'Construction4 out ...",C69135414

#### checking duplicate records

In [4]:
df.duplicated().sum()

np.int64(0)

#### checking info()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [6]:
df['property_name'].unique().tolist()

['2 BHK Flat in Krishna Colony',
 '2 BHK Flat in Ashok Vihar',
 '2 BHK Flat in Sohna',
 '2 BHK Flat in Sector 61 Gurgaon',
 '2 BHK Flat in Sector 92 Gurgaon',
 '2 BHK Flat in Sector 36 Gurgaon',
 '3 BHK Flat in Dwarka Expressway Gurgaon',
 '3 BHK Flat in Sector 104 Gurgaon',
 '2 BHK Flat in Sector 88B Gurgaon',
 '3 BHK Flat in Sector 78 Gurgaon',
 '2 BHK Flat in Sector 81 Gurgaon',
 '3 BHK Flat in Sector 79 Gurgaon',
 '2 BHK Flat in Sector 33 Gurgaon',
 '2 BHK Flat in Sector 90 Gurgaon',
 '4 BHK Flat in Sector 108 Gurgaon',
 '1 BHK Flat in Sector 62 Gurgaon',
 '2 BHK Flat in Sector 102 Gurgaon',
 '2 BHK Flat in Sector 93 Gurgaon',
 '3 BHK Flat in Sector-33 Sohna',
 '2 BHK Flat in Sector 89 Gurgaon',
 '3 BHK Flat in Sector 102 Gurgaon',
 '3 BHK Flat in Sector 113 Gurgaon',
 '5 BHK Flat in Sector 1 Gurgaon',
 '3 BHK Flat in Sector 65 Gurgaon',
 '3 BHK Flat in Sector 48 Gurgaon',
 '2 BHK Flat in Sector 37C Gurgaon',
 '2 BHK Flat in Sector 3 Gurgaon',
 '2 BHK Flat in New Palam Vihar',
 '4 BHK Flat in Sector 43 Gurgaon',
 '2 BHK Flat in Sector 88A Gurgaon',
 '3 BHK Flat in Sector 92 Gurgaon',
 '2 BHK Flat in Sector 68 Gurgaon',
 '3 BHK Flat in Sector 109 Gurgaon',
 '3 BHK Flat in Sector 43 Gurgaon',
 '3 BHK Flat in Sector 106 Gurgaon',
 '4 BHK Flat in Sector 82 Gurgaon',
 '2 BHK Flat in Ashok Vihar Phase 3 Extension',
 '3 BHK Flat in Sohna',
 '4 BHK Flat in Sector 90 Gurgaon',
 '2 BHK Flat in Sector 106 Gurgaon',
 '3 BHK Flat in Sector 85 Gurgaon',
 '3 BHK Flat in Sector 82A Gurgaon',
 '2 BHK Flat in DLF Phase 4',
 '2 BHK Flat in Sector 79 Gurgaon',
 '2 BHK Flat in Sector 10A Gurgaon',
 '4 BHK Flat in Sector 1A IMT Manesar',
 '1 BHK Flat in Block A Surya Vihar',
 '1 BHK Flat in Sector 84 Gurgaon',
 '3 BHK Flat in Sector 33 Gurgaon',
 '2 BHK Flat in Sector 71 Gurgaon',
 '2 BHK Flat in Sector-7 Housing Board',
 '4 BHK Flat in Sector 92 Gurgaon',
 '2 BHK Flat in Sector 77 Gurgaon',
 '3 BHK Flat in Sector 37D Gurgaon',
 '4 BHK Flat in Sector 67A Gurgaon',
 '3 BHK Flat in Sector 37C Gurgaon',
 '3 BHK Flat in Sector 57 Gurgaon',
 '2 BHK Flat in Sector 95 Gurgaon',
 '2 BHK Flat in Sector 99A Gurgaon',
 '2 BHK Flat in Sector 103 Gurgaon',
 '3 BHK Flat in Sector 89 Gurgaon',
 '3 BHK Flat in Sector 49 Gurgaon',
 '3 BHK Flat in Sector 90 Gurgaon',
 '3 BHK Flat in Sector 30 Gurgaon',
 '2 BHK Flat in Sector 86 Gurgaon',
 '5 BHK Flat in Sector 66 Gurgaon',
 '2 BHK Flat in Sector 15 Part 1',
 '3 BHK Flat in Sector 61 Gurgaon',
 '2 BHK Flat in Laxman Vihar',
 '2 BHK Flat in Sector 37D Gurgaon',
 '2 BHK Flat in Sector 65 Gurgaon',
 '2 BHK Flat in Sector 22 Gurgaon',
 '3 BHK Flat in Sector 63A Gurgaon',
 '3 BHK Flat in Sector 88A Gurgaon',
 '1 BHK Flat in Sohna',
 '3 BHK Flat in Sector 77 Gurgaon',
 '1 BHK Flat in Sector 109 Gurgaon',
 '1 BHK Flat in Sector 78 Gurgaon',
 '2 BHK Flat in Sector 95A Gurgaon',
 '4 BHK Flat in Sector 113 Gurgaon',
 '3 BHK Flat in Sector 103 Gurgaon',
 '3 BHK Flat in Sector 99A Gurgaon',
 '2 BHK Flat in Sector 113 Gurgaon',
 '2 BHK Flat in Sector 104 Gurgaon',
 '4 BHK Flat in Sector 52 Gurgaon',
 '1 BHK Flat in Sector 67 Gurgaon',
 '3 BHK Flat in Sector 86 Gurgaon',
 '3 BHK Flat in Sushant Lok Phase 1',
 '2 BHK Flat in Sector 107 Gurgaon',
 '4 BHK Flat in Sector 82A Gurgaon',
 '3 BHK Flat in Sector 12A Gurgaon',
 '2 BHK Flat in Sohna Road',
 '2 BHK Flat in Ashok Vihar Phase 2',
 '2 BHK Flat in Rajiv Colony',
 '3 BHK Flat in Sector 2 Gurgaon',
 '3 BHK Flat in Garauli Kalan',
 '2 BHK Flat in Sector 108 Gurgaon',
 '4 BHK Flat in Sector 37D Gurgaon',
 '3 BHK Flat in Bhawani Enclave',
 '1 BHK Flat in Sector 95 Gurgaon',
 '2 BHK Flat in Sector 99 Gurgaon',
 '3 BHK Flat in IFFCO Chowk',
 '2 BHK Flat in Sector 82A Gurgaon',
 '4 BHK Flat in Palam Vihar',
 '4 BHK Flat in Sector 91 Gurgaon',
 '4 BHK Flat in near sector 1 market',
 '3 BHK Flat in Sector 70 Gurgaon',
 '2 BHK Flat in Sector 70A Gurgaon',
 '3 BHK Flat in Gwal Pahari',
 '2 BHK Flat in Sector 7 Gurgaon',
 '3 BHK Flat in Sohna Road',
 '3 BHK Flat in Malibu Town',
 '2 BHK Flat in Golf Course Road',
 '2 BHK Flat in Sector 4 Gurgaon',
 '3 BHK Flat in Sector 99 Gurgaon',
 '4 BHK Flat in Sector 68 Gurgaon',
 '3 BHK Flat in Sector 54 Gurgaon',
 '2 BHK Flat in Sector 111 Gurgaon',
 '2 BHK Flat in Chakkarpur',
 '5 BHK Flat in Sector 82A Gurgaon',
 '4 BHK Flat in Sector 41 Gurgaon',
 '2 BHK Flat in Sector 12 Gurgaon',
 '3 BHK Flat in Sector 71 Gurgaon',
 '2 BHK Flat in Sector 84 Gurgaon',
 '3 BHK Flat in Sector 73 Gurgaon',
 '3 BHK Flat in Sector 36 Sohna',
 '3 BHK Flat in Sector 56 Gurgaon',
 '3 BHK Flat in Sector 83 Gurgaon',
 '3 BHK Flat in Sector 53 Gurgaon',
 '2 BHK Flat in Sector-33 Sohna',
 '3 BHK Flat in Sector 62 Gurgaon',
 '4 BHK Flat in Sector 78 Gurgaon',
 '3 BHK Flat in Sector 4 Gurgaon',
 '4 BHK Flat in Sector 72 Gurgaon',
 '4 BHK Flat in Sector 1 Imt Manesar',
 '3 BHK Flat in Sector 70A Gurgaon',
 '3 BHK Flat in Sector 69 Gurgaon',
 '3 BHK Flat in Sector 82 Gurgaon',
 '2 BHK Flat in Sector 47 Gurgaon',
 '2 BHK Flat in Sector 70 Gurgaon',
 '1 BHK Flat in Sector 83 Gurgaon',
 '1 BHK Flat in Sector 63 Gurgaon',
 '4 BHK Flat in Sector 110 Gurgaon',
 '3 BHK Flat in Palam Vihar',
 '3 BHK Flat in Sector 84 Gurgaon',
 '4 BHK Flat in Sector 33 Gurgaon',
 '3 BHK Flat in Kanahi',
 '2 BHK Flat in Sector-11 sohna',
 '3 BHK Flat in Sector 67 Gurgaon',
 '2 BHK Flat in Sector 62 Gurgaon',
 '3 BHK Flat in DLF Phase 5',
 '4 BHK Flat in Sector 9A Gurgaon',
 '2 BHK Flat in Sector 85 Gurgaon',
 '1 BHK Flat in Sector 28 Gurgaon',
 '5 BHK Flat in Sector 14 Gurgaon',
 '4 BHK Flat in Sector 86 Gurgaon',
 '3 BHK Flat in Nirvana Country',
 '4 BHK Flat in DLF Phase 2',
 '4 BHK Flat in Sector 111 Gurgaon',
 '3 BHK Flat in Sector 108 Gurgaon',
 '4 BHK Flat in Sector 48 Gurgaon',
 '3 BHK Flat in Sector 59 Gurgaon',
 '3 BHK Flat in Sector 66 Gurgaon',
 '2 BHK Flat in Palam Vihar',
 '3 BHK Flat in DLF Phase 4',
 '4 BHK Flat in Sector 22 Gurgaon',
 '3 BHK Flat in Sector 9A Gurgaon',
 '4 BHK Flat in DLF Phase 3',
 '3 BHK Flat in Heritage City',
 '4 BHK Flat in Sector 103 Gurgaon',
 '4 BHK Flat in Gwal Pahari',
 '4 BHK Flat in Sector 1 Gurgaon',
 '4 BHK Flat in Sector 38 Gurgaon',
 '3 BHK Flat in DLF Phase 3',
 '4 BHK Flat in Sector 15 Gurgaon',
 '3 BHK Flat in Ambience Island',
 '4 BHK Flat in Ambience Island',
 '3 BHK Flat in Sector 1A IMT Manesar',
 '3 BHK Flat in Sector 81 Gurgaon',
 '5 BHK Flat in Sector 110 Gurgaon',
 '4 BHK Flat in Sector 56 Gurgaon',
 '2 BHK Flat in Sector 30 Gurgaon',
 '3 BHK Flat in Sector 112 Gurgaon',
 '4 BHK Flat in Sector 112 Gurgaon',
 '4 BHK Flat in Sector 84 Gurgaon',
 '3 BHK Flat in Sector 47 Gurgaon',
 '5 BHK Flat in Sector 106 Gurgaon',
 '4 BHK Flat in Sector 65 Gurgaon',
 '3 BHK Flat in Sector 45 Gurgaon',
 '4 BHK Flat in Sector 62 Gurgaon',
 '4 BHK Flat in Sector 77 Gurgaon',
 '4 BHK Flat in Sector 54 Gurgaon',
 '3 BHK Flat in Sector 74 Gurgaon',
 '4 BHK Flat in Sector 61 Gurgaon',
 '3 BHK Flat in Sector 60 Gurgaon',
 '3 BHK Flat in Sector 72 Gurgaon',
 '4 BHK Flat in Sector 69 Gurgaon',
 '4 BHK Flat in Sector 107 Gurgaon',
 '3 BHK Flat in Sector 22 Gurgaon',
 '2 BHK Flat in Sector 74 Gurgaon',
 '1 BHK Flat in Sector 2 Gurgaon',
 '4 BHK Flat in Sector 47 Gurgaon',
 '3 BHK Flat in Sector 1 Imt Manesar',
 '2 BHK Flat in Sector 112 Gurgaon',
 '5 BHK Flat in Sector 51 Gurgaon',
 '3 BHK Flat in Sector 107 Gurgaon',
 '3 BHK Flat in Sector 50 Gurgaon',
 '1 BHK Flat in Palam Vihar',
 '4 BHK Flat in Sector 60 Gurgaon',
 '4 BHK Flat in Sector 81 Gurgaon',
 '4 BHK Flat in Sector 85 Gurgaon',
 '2 BHK Flat in Sector 60 Gurgaon',
 '4 BHK Flat in Sector 67 Gurgaon',
 '2 BHK Flat in Sector 78 Gurgaon',
 '4 BHK Flat in Suncity',
 '4 BHK Flat in Sector 110 A Gurgaon',
 '4 BHK Flat in Sector 83 Gurgaon',
 '2 BHK Flat in Sector 83 Gurgaon',
 '4 BHK Flat in Sector 70 Gurgaon',
 '3 BHK Flat in Sector 39 Gurgaon',
 '5 BHK Flat in Sector 39 Gurgaon',
 '1 BHK Flat in Sector 92 Gurgaon',
 '5 BHK Flat in Gwal Pahari',
 '4 BHK Flat in Sector 49 Gurgaon',
 '3 BHK Flat in Sector 95 Gurgaon',
 '4 BHK Flat in Sector 104 Gurgaon',
 '4 BHK Flat in Sector 106 Gurgaon',
 '4 BHK Flat in Sector 102 Gurgaon',
 '3 BHK Flat in Sai Kunj',
 '2 BHK Flat in Sector 67A Gurgaon',
 '3 BHK Flat in Manesar',
 '3 BHK Flat in Sector 1 Gurgaon',
 '4 BHK Flat in DLF Phase 5',
 '3 BHK Flat in sector 58 Gurgaon',
 '4 BHK Flat in Sector 53 Gurgaon',
 '2 BHK Flat in Nirvana Country',
 '5 BHK Flat in Sector 113 Gurgaon',
 '3 BHK Flat in Sector 111 Gurgaon',
 '4 BHK Flat in Sector 109 Gurgaon',
 '5 BHK Flat in Sector 83 Gurgaon',
 '4 BHK Flat in Sector 71 Gurgaon',
 '4 BHK Flat in Sector 66 Gurgaon',
 '3 BHK Flat in Sector 110 A Gurgaon',
 '3 BHK Flat in Sector 63 Gurgaon',
 '2 BHK Flat in Sector 82 Gurgaon',
 '3 BHK Flat in Sector 52 Gurgaon',
 '2 BHK Flat in Sector 91 Gurgaon',
 '3 BHK Flat in Sector 91 Gurgaon',
 '4 BHK Flat in Sector 99A Gurgaon',
 '5 BHK Flat in Sector 49 Gurgaon',
 '2 BHK Flat in Sector 66 Gurgaon',
 '4 BHK Flat in Sector 39 Gurgaon',
 '1 BHK Flat in Sector 103 Gurgaon',
 '2 BHK Flat in Sector 69 Gurgaon',
 '3 BHK Flat in IMT Manesar',
 '4 BHK Flat in Sector 70A Gurgaon',
 '5 BHK Flat in Sector 62 Gurgaon',
 '2 BHK Flat in Sector 1 Imt Manesar',
 '1 BHK Flat in Sector 71 Gurgaon',
 '4 BHK Flat in Sector 37C Gurgaon',
 '3 BHK Flat in Sector 80 Gurgaon',
 '3 BHK Flat in MG Road',
 '4 BHK Flat in sector 58 Gurgaon',
 '2 BHK Flat in sector 58 Gurgaon',
 '3 BHK Flat in Sector 55 Gurgaon',
 '3 BHK Flat in Sultanpur',
 '4 BHK Flat in Sector 59 Gurgaon',
 '3 BHK Flat in Sector 68 Gurgaon',
 '4 BHK Flat in Sushant Lok Phase 1',
 '1 BHK Flat in Sector 81 Gurgaon',
 '3 BHK Flat in Suncity',
 '3 BHK Flat in Sector 67A Gurgaon',
 '4 BHK Flat in MG Road',
 '4 BHK Flat in Sector 50 Gurgaon',
 '1 BHK Flat in Sector 106 Gurgaon',
 '4 BHK Flat in Sector-33 Sohna',
 '2 BHK Flat in Sector 23A Gurgaon',
 '2 BHK Flat in Sector 51 Gurgaon',
 '1 BHK Flat in Sector 36A Gurgaon',
 '1 BHK Flat in Sector 56 Gurgaon',
 '1 BHK Flat in Sector 111 Gurgaon',
 '1 BHK Flat in Sector 52 Gurgaon',
 '3 BHK Flat in Civil Lines',
 '3 BHK Flat in Sector 28 Gurgaon',
 '3 BHK Flat in Sector 76 Gurgaon',
 '5 BHK Flat in Sector 57 Gurgaon',
 '3 BHK Flat in New Colony, Sector 7',
 '1 BHK Flat in Sector 31 Gurgaon',
 '3 BHK Flat in Sector 31 Gurgaon',
 '2 BHK Flat in Sector 67 Gurgaon',
 '4 BHK Flat in Sector 31 Gurgaon',
 '3 BHK Flat in Lajpat Nagar',
 '2 BHK Flat in Sector 89 A Gurgaon',
 '2 BHK Flat in Sector 63A Gurgaon',
 '4 BHK Flat in Sector 51 Gurgaon',
 '2 BHK Flat in Sector 2 Gurgaon',
 '3 BHK Flat in Sector 7 Gurgaon',
 '1 BHK Flat in Sector 63A Gurgaon',
 '1 BHK Flat in Sector 51 Gurgaon',
 '2 BHK Flat in Sector 73 Gurgaon',
 '4 BHK Flat in New Gurgaon',
 '3 BHK Flat in Sector 89 A Gurgaon',
 '2 BHK Flat in Sector 36A Gurgaon',
 '4 BHK Flat in Sector 63 Gurgaon',
 '3 BHK Flat in Chakkarpur',
 '2 BHK Flat in Sector 11 Gurgaon',
 '1 BHK Flat in Sector 104 Gurgaon',
 '3 BHK Flat in Sector 32 Gurgaon',
 '4 BHK Flat in Sector 79 Gurgaon',
 '2 BHK Flat in Gwal Pahari',
 '6 BHK Flat in Sector 10A Gurgaon',
 '5 BHK Flat in DLF Phase 2',
 '5 BHK Flat in Surya Vihar',
 '2 BHK Flat in Near Pataudi Chowk',
 '4 BHK Flat in Cyber City',
 '3 BHK Flat in New Colony',
 '3 BHK Flat in Sector 51 Gurgaon',
 '2 BHK Flat in Subhash Nagar',
 '4 BHK Flat in Sector 93 Gurgaon',
 '5 BHK Flat in Sector 48 Gurgaon',
 '3 BHK Flat in ats marigold',
 '3 BHK Flat in Sector 15 Gurgaon',
 '3 BHK Flat in Sector 36A Gurgaon',
 '2 BHK Flat in Sector-2 Sohna',
 '3 BHK Flat in Adarsh Nagar',
 '2 BHK Flat in Sector 76 Gurgaon',
 '4 BHK Flat in Sector 37A Gurgaon',
 '4 BHK Flat in Sector 45 Gurgaon',
 '3 BHK Flat in Sushant Lok Phase 3',
 '2 BHK Flat in Carterpuri Village',
 '1 BHK Flat in Sector 102 Gurgaon',
 '2 BHK Flat in Sector 31 Gurgaon',
 '4 BHK Flat in Valley View Estate',
 '3 BHK Flat in Shanti Nagar',
 '4 BHK Flat in Sushant Lok',
 '4 BHK Flat in Mehrauli Gurgaon Road',
 '1 BHK Flat in Laxman Vihar Phase 2',
 '2 BHK Flat in Sector-5 Sohna',
 '2 BHK Flat in Gurgaon Faridabad Road',
 '1 BHK Flat in Sector 107 Gurgaon',
 '1 BHK Flat in Sector 36 Gurgaon',
 '3 BHK Flat in Sector 5 chowk Gurgaon',
 '2 BHK Flat in Manesar',
 '5 BHK Flat in old delhi road, opp sector-14',
 '1 BHK Flat in Sector 47 Gurgaon',
 '1 BHK Flat in Sector 49 Gurgaon',
 '5 BHK Flat in Sector 21 Gurgaon',
 '1 BHK Flat in Sector 5 Gurgaon',
 '4 BHK Flat in Chakkarpur',
 '1 BHK Flat in Sector 89 A Gurgaon',
 '1 BHK Flat in Sector 82A Gurgaon',
 '5 BHK Flat in Sector 52 Gurgaon',
 '3 BHK Flat in Dayanand Colony',
 '1 BHK Flat in Sector 37C Gurgaon',
 '2 BHK Flat in Samaspur',
 '3 BHK Flat in Nirvana country Pocket H',
 '4 BHK Flat in Sector 95 Gurgaon',
 '4 BHK Flat in Sector 76 Gurgaon',
 '3 BHK Flat in Ashok Vihar Phase 2',
 '2 BHK Flat in Patel Nagar',
 '1 BHK Flat in Surat Nagar 1',
 '1 BHK Flat in Sispal Vihar',
 '3 BHK Flat in Golf Course Ext Road',
 '4 BHK Flat in Shankar Vihar',
 '4 BHK Flat in Sector 99 Gurgaon',
 '3 BHK Flat in Sector-2 Sohna',
 '3 BHK Flat in Sector 93 Gurgaon',
 '2 BHK Flat in New Palam Vihar Phase 2',
 '4 BHK Flat in Sector 24 Gurgaon',
 '4 BHK Flat in Adarsh Nagar',
 '3 BHK Flat in Sector 12 Gurgaon',
 '3 BHK Flat in Mehrauli Gurgaon Road',
 '6 BHK Flat in Sector 70 Gurgaon',
 '4 BHK Flat in Sector 55 Gurgaon',
 '2 BHK Flat in Sector-35 Sohna',
 '2 BHK Flat in Sector 110 Gurgaon',
 '3 BHK Flat in Bhondsi',
 '1 BHK Flat in Palam Vihar Extension',
 '2 BHK Flat in New Gurgaon',
 '2 BHK Flat in saroop garden rajendra park',
 '2 BHK Flat in Dayanand Colony',
 '1 BHK Flat in Sector 80 Gurgaon',
 '3 BHK Flat in Sector 10A Gurgaon',
 '2 BHK Flat in Sector 4 Urban Estate',
 '3 BHK Flat in BPTP',
 '3 BHK Flat in Sector 105 Gurgaon',
 '3 BHK Flat in South City 1',
 '2 BHK Flat in Valley View Estate',
 '4 BHK Flat in Sector 88A Gurgaon',
 '4 BHK Flat in Sector 9 Gurgaon',
 '1 BHK Flat in Valley View Estate',
 '2 BHK Flat in Shanti Nagar',
 '2 BHK Flat in Sushant Lok Phase 3',
 '1 BHK Flat in Golf Course Ext Road',
 '4 BHK Flat in C Block Sushant Lok Phase 1',
 '3 BHK Flat in Ashok Vihar',
 '2 BHK Flat in Sector 21 Gurgaon',
 '1 BHK Flat in Sector 40 Gurgaon',
 '2 BHK Flat in Dharam Colony',
 '4 BHK Flat in Golf Course Ext Road',
 '4 BHK Flat in DLF Phase 4',
 '3 BHK Flat in Rajendra Park',
 '2 BHK Flat in Godrej Aria , sector 79 , Gurgaon',
 '3 BHK Flat in Dharam Colony']

In [7]:
df['society'].unique().tolist()

['maa bhagwati residency',
 'Apna Enclave',
 'Tulsiani Easy in Homes',
 'Smart World Orchard',
 'Parkwood Westend',
 'Signature Global Infinity Mall',
 'The Cocoon',
 'ATS Triumph3.9 ★',
 'Vatika Xpressions',
 'Raheja Revanta',
 'Signature Global City 81',
 'HCBS Sports Ville3.6 ★',
 'Supertech Araville',
 'Godrej',
 'Shree Vardhman Flora3.8 ★',
 'Sobha City',
 'Senate Court',
 'Shapoorji Pallonji Joyville Gurugram4.0 ★',
 'Signature Global Orchard Avenue 2',
 'Central Park Flower Valley',
 'Smart World Gems',
 'Bestech Altura',
 'Emaar Imperial Gardens3.8 ★',
 'La Vida by Tata Housing',
 'The New People Apartments',
 'The Serenas',
 'M3M Golfestate4.4 ★',
 'Central Park Resort Belgravia Residences',
 'Apex builders',
 'Godrej Habitat',
 'Ompee K S Residency',
 'Bhawna CGHS',
 'Adani Aangan Arcade',
 'Sare Green Parc',
 'Supertech Hues',
 'Chintels Paradiso3.9 ★',
 'Breez Global Hill View',
 'ILD Greens4.1 ★',
 'Ansal Sushant Lok CI',
 'Ashiana Mulberry',
 'Godrej Meridien',
 'Mapsko Casa Bella3.8 ★',
 'Pooja Apartment',
 'Signature Global Park4.0 ★',
 'DLF New Town Heights 13.9 ★',
 'Paras Dews',
 'Godrej Air',
 'DLF The Primus3.9 ★',
 'Emaar MGF Emerald Floors Premier3.8 ★',
 'DLF Regency Park 13.6 ★',
 'Maxworth City Residences',
 'Deepak Minda',
 'Shree Shyam residency',
 'Pivotal Devaan',
 'Unitech The Residences3.7 ★',
 'CHD Avenue 713.6 ★',
 'Gokuldham Society, Bahadurgarh',
 'Silverglades The Melia',
 'Sare Crescent Parc Royal Greens Phase 1',
 'Umang Winter Hills3.9 ★',
 'Ramprastha Skyz',
 '4S Aradhya Homes',
 'BPTP Freedom Park Life4.0 ★',
 'Ramsons Kshitij3.7 ★',
 'Sidhartha NCR One',
 'Raheja Sampada',
 'Signature The Serenas',
 'Pareena Laxmi Apartments3.6 ★',
 'Satya The Hermitage3.5 ★',
 'GLS Arawali Homes3.8 ★',
 'Bestech Park View City 23.9 ★',
 'AFNHB Jalvayu Vihar3.7 ★',
 'M3M Soulitude',
 'Pyramid Elite',
 'Emaar MGF Palm Terraces',
 'Anamika Enclave',
 'Puri The Aravallis',
 'Brisk Lumbini Terrace Homes',
 'HUDA Ashok Vihar Phase 13.9 ★',
 'My Home',
 'Signature Global City',
 'M3M Heights',
 'Godrej Nature Plus',
 'Central Park Flower Valley Aqua Front Towers',
 'Ambience Creacions',
 'Signature Global City 63A',
 'Godrej Oasis3.9 ★',
 'M3M Skycity',
 'Emaar Palm Premier',
 'Godrej Aria3.8 ★',
 'Conscient One',
 'Signature The Roselia3.6 ★',
 'Not Applicable',
 'Ramprastha City',
 'Smartworld 1DXP',
 'Ansal Housing Highland Park',
 'Czar Mahira Homes 63A',
 'Breez Global Heights4.2 ★',
 'Trisara Our Homes 3',
 'Emaar MGF Palm Hills4.0 ★',
 'Pareena Coban Residences',
 'Godrej Summit Premia Towers',
 'Ardee City3.8 ★',
 'M3M One Key Resiments',
 'Ansal Heights 86',
 'MVN Athens3.7 ★',
 'Sushant Lok 1 Builder Floors',
 'Umang Monsoon Breeze',
 'GLS Avenue 51',
 'Signature Global Solera3.7 ★',
 'Greenopolis',
 'Sare Homes',
 'Vatika Sovereign Next Sector-82 A Gurgaon',
 'Bhagwati sadan',
 'micasa sec 68',
 'Eldeco Accolade3.8 ★',
 'Hero Homes',
 'Shyam Sadan',
 'hanumanta apartment',
 'Supertech Hilltown',
 'ashiyara 2',
 'Raheja Vedaanta3.6 ★',
 'BPTP Terra3.8 ★',
 'Green Court3.7 ★',
 'M3M Golf Hills Phase 1',
 'Abhinav Group Housing Society',
 'Pyramid Urban Homes 2',
 'Ashiana Anmol3.5 ★',
 'Signature Signum 95A',
 'Aardhya homesh',
 'ROF Ananda',
 'Assotech Blith',
 'Essel Tower',
 'Raheja Vanya',
 'Vatika INXT Floors',
 'Palam Vihar Society',
 'DLF New Town Heights3.7 ★',
 'sonata group housing society sector 1 Manesar',
 'Krrish Florence Estate',
 'Piedmont Taksila heights3.6 ★',
 'Experion Heartsong',
 'SS The Leaf3.8 ★',
 'M3M Urbana',
 'AIPL Zen Residences',
 'DLF Regal Gardens3.9 ★',
 'Suncity Vatsal Valley',
 'Shree shyam residency',
 'Project Krishna Colony',
 'M3M Antalya Hills',
 'M3M Capital',
 'Ansal Heights3.2 ★',
 'Malibu Towne',
 'JMD Empire',
 'Housing Apna Enclave3.7 ★',
 'Pareena Mi Casa',
 'Suncity Heights3.7 ★',
 'Lotus Homz4.0 ★',
 'Ramson kshitij Sec-95 Gurugram',
 'Maruti Vihar Colony',
 'Supertech Basera',
 'Signature Global the Millennia',
 'Ganpati apartment  2, Laxman Vihar Phase 1',
 'Ramprastha The Atrium3.4 ★',
 'M3M Golfestate',
 'Vatika Sovereign Next',
 'South City 1 Floors',
 'Allure Homes',
 'Zara Aavaas',
 'Sidhartha NCR One Phase 14.2 ★',
 'Ramprastha The Edge Towers3.5 ★',
 'Imperia Aashiyara',
 'Today Callidora',
 'M M Residency, Krishna Colony, Gurgaon',
 'Signature Global Park 4',
 'Park Royal Apartment',
 'Vatika Boulevard Residences and Heights',
 'Tulip Monsella',
 'Shyamkunj ashok vihar pahse 2',
 'M3M The Marina4.0 ★',
 'Emaar Digihomes',
 'Mapsko Paradise3.9 ★',
 'Cancon Enclave',
 'Tata Primanti4.1 ★',
 'MRG World Ultimus',
 'sonata group housing Gh 24',
 'BPTP Pedestal',
 'HSIIDC Sidco Aravali',
 'Sare Crescent Parc3.5 ★',
 'Unitech Vistas',
 'Tulip White3.5 ★',
 'Unitech Uniworld Gardens 23.4 ★',
 'ILD Grand',
 'Sapphire Eighty Three',
 'DLF The Grove',
 'Baani City Center',
 'Indiabulls Enigma',
 'Smart World One DXP',
 'Sukhshanti Apartment',
 'Bestech Park View Residency3.9 ★',
 'SS Almeria',
 'JMD Gardens4.4 ★',
 'CGHS Agrim Apartment',
 'Global Hill View',
 'Ireo Victory Valley4.1 ★',
 'DLF Carlton Estate4.0 ★',
 'Railway Officers RPF Society',
 'Maruti Vihar',
 'Vasant Appartments',
 'The Close North4.0 ★',
 'Emaar Gurgaon Greens4.1 ★',
 'Landmark The Residency',
 'DLF Belvedere Towers3.8 ★',
 'm3m crown',
 'Godrej 1014.0 ★',
 'Central Park Resorts4.4 ★',
 'AIPL Club Residences',
 'Experion The Heartsong3.9 ★',
 'Bestech Park View City4.1 ★',
 'Emaar Palm Gardens4.1 ★',
 'Mahindra Luminare4.0 ★',
 'Raheja Navodaya3.6 ★',
 'Emaar MGF The Palm Drive4.1 ★',
 'M3M Merlin3.7 ★',
 'DLF The Skycourt',
 'DLF Regency Park 24.0 ★',
 'Signature Global City 92',
 'The Khushboo Cooperative Housing Society Ltd3.9 ★',
 'Adani M2K Oyster Grande3.9 ★',
 'DLF City Plots Phase 3',
 'Unitech Heritage City',
 'Indiabulls Centrum Park3.7 ★',
 'Orris Aster Court Premier',
 'Paras Quartier',
 'Samadhan Shri Kamal CGHS',
 'Navjyoti Apartment',
 'Ambience Lagoon3.9 ★',
 'Orchid Petals4.1 ★',
 'Friends Apartment',
 'The Close South3.9 ★',
 'CGHS Rail Vihar4.0 ★',
 'lagoon apartment',
 'Orris Carnation Residency3.7 ★',
 'Sbr minda sec 1 imt manesar',
 'DLF The Ultima4.0 ★',
 'The Lions CGHS',
 'Experion Windchants3.8 ★',
 'Antriksh Heights3.7 ★',
 'Unitech Uniworld Gardens3.8 ★',
 'Elan The Presidential',
 'Raheja Atharva3.6 ★',
 'Mapsko Royale Ville3.7 ★',
 'Unitech Greenwood City3.6 ★',
 'ATS Tourmaline3.9 ★',
 'TARC Maceo3.8 ★',
 'Pioneer Urban Presidia',
 'La Lagune',
 'M3M Latitude',
 'M3M Skywalk',
 'Pioneer Park3.8 ★',
 'Ireo Skyon4.0 ★',
 'Bestech Park View Ananda4.2 ★',
 'Tulip Purple',
 'SBTL Caladium',
 'Vatika The Seven Lamps3.8 ★',
 'M3M Woodshire4.0 ★',
 'Parsvnath Green Ville3.9 ★',
 'Conscient Heritage Max4.3 ★',
 'Emaar MGF Emerald Estate3.8 ★',
 'Puri Emerald Bay3.7 ★',
 'Ansal API Celebrity Suites',
 'CGHS Airport Apartment',
 'Sbr minda sec-1 imt manesar',
 'Prasha Apartments',
 'Vatika Independent Floors3.8 ★',
 'Citizen apartment',
 'Kiran Residency',
 'SS The Coralwood3.4 ★',
 'Eros Wembley Estate3.9 ★',
 'Alpha Corp GurgaonOne 844.0 ★',
 'Imperia The Esfera',
 'Shree Vardhman Victoria3.8 ★',
 'Bestech Park View Grand Spa4.3 ★',
 'Bestech Park View Spa Next4.0 ★',
 'Vatika Gurgaon 213.7 ★',
 'Bestech Spa Signature',
 'Bestech Park View Sanskruti4.2 ★',
 'Swarn Jayanti CGHS',
 'AIPL The Peaceful Homes3.9 ★',
 'Emaar Palm Heights',
 'Parsvnath Exotica3.7 ★',
 'Shree Arihant Apartment',
 'Mahindra Aura4.2 ★',
 'Krrish Provence Estate',
 'Sare Green ParC Phase 3',
 'Shri Banke Bihari Society3.8 ★',
 'DLF New Town Heights 24.0 ★',
 'ATS Kocoon',
 'Orris Aster Court',
 'Godrej Icon',
 'Green Campus CHS',
 'Tulip Ivory3.5 ★',
 'Mapsko Mount Ville4.1 ★',
 'City Heights',
 'KW Royal Court',
 'Kamroon Court',
 'DLF The Crest3.6 ★',
 'DLF The Skycourt4.2 ★',
 'Saan Verdante',
 'Tulip Violet4.2 ★',
 'Vatika City Homes3.9 ★',
 'Puri Diplomatic Greens4.0 ★',
 'Laxmi Apartment',
 'Ireo The Corridors',
 'Denso Haryana Housing Society',
 'The Nav Manesar Apartment',
 'DLF The Icon3.7 ★',
 'Professors Enclave CGHS',
 'Ansal Maple Heights3.7 ★',
 'Ireo The Grand Arch4.0 ★',
 'Capital Residences 360',
 'Signature Global Synera3.4 ★',
 'Emaar Emerald Hills4.1 ★',
 'Unitech Fresco3.8 ★',
 'Ansal Maple Crescent',
 'Prime Habitat',
 'Puri Diplomatic Greens3.9 ★',
 'Tata Gurgaon Gateway3.8 ★',
 'Tulip Violet4.3 ★',
 'Sunischit Apartments',
 'BPTP Mansions Park Prime',
 'Dhoot Time Residency4.0 ★',
 'DLF Wellington Estate4.2 ★',
 'Vatika City4.1 ★',
 'PGR Shree Kripaluji Apartment',
 'ATS Kocoon4.2 ★',
 'Sagar Apartment',
 'Paras Irene3.7 ★',
 'Pyramid Urban',
 'DLF Exclusive Floors4.1 ★',
 'DLF Ridgewood Estate3.9 ★',
 'Corona Optus3.9 ★',
 'M3M Sierra 68',
 'Pioneer Araya3.8 ★',
 'DLF Trinity Towers3.7 ★',
 'DLF Park Place4.1 ★',
 'Vatika Lifestyle Homes3.8 ★',
 'Ireo Uptown4.1 ★',
 'BPTP Astaire Gardens3.7 ★',
 'Unitech Uniworld City3.8 ★',
 'Hector Trimurti Heights',
 'Emaar Mgf Palm Terraces Select3.8 ★',
 '.',
 'Unitech Harmony',
 'Godrej Summit3.7 ★',
 'Spaze Privy3.9 ★',
 'Signature Global Grand IVA3.9 ★',
 'Tulip Lemon3.9 ★',
 'Professional Society',
 'HSIIDC Sidco Shivalik Apartments3.8 ★',
 'IMT View Society',
 'Signature Andour Heights3.8 ★',
 'Conscient Habitat3.6 ★',
 'Mariners Home',
 'Meditech Apartment',
 'shree kirpalu gi sector 52',
 'Godrej Frontier3.7 ★',
 'DLF The Belaire3.9 ★',
 'Suncity Platinum Towers',
 'Spaze Privy AT43.9 ★',
 'Suncity Avenue 1023.9 ★',
 'BPTP Amstoria3.8 ★',
 'Rail Vihar CGHS3.9 ★',
 'Microtek Greenburg3.8 ★',
 'Apex Our Homes',
 'Ramprastha Primera',
 'Emaar MGF The Enclave',
 'Vipul Belmonte3.9 ★',
 'Siddhi Vinayak Apartments',
 'Madhur Jeevan Apartments',
 'Guru Gram Haryana CGHS4.1 ★',
 'Park View Apartment',
 'Empire estate',
 'SS The Leaf',
 'ss',
 'Raisina Residency3.7 ★',
 'Signature Global Orchard Avenue3.6 ★',
 'Bestech Park View Sanskruti4.1 ★',
 'M3M Ikonic',
 'Beverley park 1',
 'New Sathi Apartments',
 'Kanchanjanga Tower',
 'Millenium Bajrang Society3.8 ★',
 'The Penthouses at the Hibiscus',
 'SS Hibiscus',
 'Siddhartha Apartment',
 'Adani Oyster Greens',
 'Viridian The Plaza 106',
 'Vatika Iris Floors',
 'Tulip Leaf',
 'Tulip Violet',
 'Vatika Emilia Floors3.7 ★',
 'The Crew Bos Chs Manesar',
 'Nagata Group Housing Society',
 'Emaar MGF Palm Studios',
 'Ashiana Apartment',
 'Orchid Island4.2 ★',
 'Vipul Lavanya3.9 ★',
 'Vipul World3.9 ★',
 'Signature Global The Millennia 3',
 'AVL 36 Gurgaon3.7 ★',
 'Kendriya Vihar4.1 ★',
 'M3M Sky Lofts',
 'Ansal API Sushant Estate4.1 ★',
 'AWHO Sispal Vihar4.0 ★',
 'ROF Aalayas3.8 ★',
 'Green Homes',
 'AWHO Shanti Vihar4.0 ★',
 'Ansal API Esencia3.7 ★',
 'Dron Apartment',
 'Rose Apartment',
 'The Rama Apartment CGHS',
 'Whiteland Blissville',
 'shyam apartment',
 'Signature Global Solera 2',
 'Raheja Atlantis3.8 ★',
 'Raheja Teachers Apartments3.1 ★',
 'Laxmi pareena',
 'The New CRPF Apartments',
 'Pivotal Riddhi Siddhi',
 'Shree Vardhman Mantra3.7 ★',
 'Tashee Capital Gateway',
 'Builder Floor',
 'Adani Brahma Samsara Vilasa',
 'Central Park 2 Bellevue',
 'Tulip Orange3.9 ★',
 'Birla Navya',
 'Signature Global City 37D Ph 2',
 'Woodstock Floors',
 'Adani Aangan Galleria',
 'The Arzoo CGHS',
 'HCBS Sports Ville',
 'Smartworld One DXP',
 'Unitech Sunbreeze',
 'RWA',
 'Radhakrishna society',
 'AIPL Joy Square',
 'Housing Board Colony',
 'Dlf 76',
 'ATS Marigold',
 'DLF Icon',
 'DLF The Arbour',
 'Sahara Grace',
 'Aipl Peaceful Homes',
 'Huda Housing Board Society',
 'Chintamani',
 'Aqua Front Towers',
 'Sare Green Parc 2',
 'DLF Express Greens3.9 ★',
 'Signature Global Superbia',
 'Karmyogi Apartment',
 'DLF Beverly Park4.1 ★',
 'Surya Vihar RWA',
 'Floor type society',
 'M3m Golf Hills',
 'Elevate',
 'Pivotal Devaan Apartments',
 'Conscient Elevate',
 'on request',
 'Raheja Maheshwara',
 'Dlf 3 Apartment',
 'New colony, Gurgaon',
 'Oriental Valley CHS',
 '511 sarahah tower',
 'Spaze Privvy The Address3.9 ★',
 'Supertech New Soft Launch',
 'Emaar Mgf Emerald Floors3.9 ★',
 'Belgravia Resort Residences',
 'Tulip Yellow',
 'BPTP Park Generations3.7 ★',
 'Shri Ram Apartments',
 'BSF CHS',
 'Kibithu Villas',
 'dnha group housing society',
 'NBCC Heights3.9 ★',
 'Malibu Towers',
 'Park View Apartments',
 'Tulip Petals3.6 ★',
 'Ansal Plaza',
 'Krisumi Waterfall Residences',
 'Supertech Hill Town',
 'Emaar The Palm Drive',
 'Raheja The Vedaanta Floors',
 'kamal residence',
 'Adarsh nagar',
 'g l s arawali homes',
 'Suncity Avenue 76',
 'ILD Greens',
 'Godrej Nature Plus Serenity',
 'Antriksh Green',
 'Whiteland The Aspen',
 'Ansal Height 86',
 'Ramsons Kshitij',
 'Ashiana Anmol',
 'Ansal Sushant Residency',
 'Ashray Apartment',
 'Sidhartha NCR Greens4.3 ★',
 'CGHS Hewo Apartments3.7 ★',
 'Valley View Estate',
 'Raheja Vedas',
 'Ganga Apartment',
 'Surbhi Apartment',
 'Espire South',
 'The Castle Society3.8 ★',
 'Essel Towers',
 'ShreeRam Apartment II',
 'The Roselia 2',
 'Mvn athens sohna gurgaon',
 'Ace Palm Floors',
 'Ansal Valley View Estate',
 'The Millennia 2',
 'dlf the arbour',
 'Breez Global Heights',
 'Global height',
 'Aashirwad Residency',
 'Whiteland  The ASPEN',
 'Eden Landmark',
 'CGHS Vidya Enclave3.9 ★',
 'Vasant Apartment',
 'IRWO Westend Towers3.9 ★',
 'AFNHB Jalvayu Vihar',
 'Godrej 101, Sector 79',
 'Satya Element One',
 'Breez Global Heights 88A',
 'Pyramid Pride',
 'Suposhaa Smartworld Orchard',
 'Mittal Surya Vihar',
 'Kendriya Vihar',
 'om apartment Dayanand colony',
 'Unitech South Park',
 'The Ivy',
 'MRG Skyline',
 'Spectrum Centre',
 'Vatika India Next4.1 ★',
 'Residency Grand',
 'SS Residency',
 'Imperia Elvedor',
 'Sare Petioles',
 'Samaspurkunj',
 'Unitech Fresco',
 'essel tower',
 'Vatika Seven Elements',
 'DLF Garden City Floors',
 'Corona Gracieux',
 'om appartments',
 'the pearl apartmen',
 'Lavanya Apartments',
 'DLF Royalton Tower',
 'Shapoorji Pallonji Joyville Gurugram',
 'Kashish Manor One',
 'Apartment',
 'Vipul World Floors',
 'Milan CGHS 9',
 'Element One Service',
 'DNHA CGHS',
 'Breeze Global Heights',
 'pareena micasa',
 'Shapoorji Pallonji Joyville',
 'Dlf City',
 'Silverglades Hightown Residences',
 'Vatika Sovereign Park',
 'SBR apartment',
 'Surendra Avenue 69',
 'Krishna Apartment',
 'Ambience Caitriona',
 'Lord Krishna',
 'Bhagwati Sadan',
 'Central Park Flower Valley Cerise Floors',
 'Sidhivinayak Apartments',
 'Ashok vihar phase 2',
 'Sobha Smriti Apartments',
 'ILD Grand Centra',
 'Ansals Highland Park',
 nan,
 'Smriti Apartment',
 'Shyam Apartment',
 'City Shri Ram Apartments 1',
 'Maruti Kunj',
 'Palam Vihar Extension West Zone RWA',
 'Vidya Apartment',
 'takshila heights sector 37 c',
 'saroop garden',
 'M3M The Tree Of Life',
 'bajrang apartments',
 'Elan Mercado',
 'Sanskriti Apartment',
 'smart world one',
 'ramshanti cooperative society',
 'SS Radiance Residency',
 'rk tower',
 'Emaar Mgf Emerald Floors',
 'Uphaar Homes',
 'Unitech The Palms',
 'Lotus Elise',
 'NUL',
 'signature global rosellia',
 'Divya Apartments',
 'The Center Court',
 'Uphaar Residency 2',
 'Wings Apartment',
 'Bhemerlei',
 'Earth Copia',
 'Proxima Tower',
 'Green Court',
 'shree balaji appartment',
 'Ansal Harmony Homes3.7 ★',
 'Mittal Cosmos Executive Apartments3.8 ★',
 'ikon tower baani city centre',
 'Maple Heights',
 'Jammu and Kashmir Bank Employees CGHS3.7 ★',
 'Ramprasta AWHO',
 'Aditya Apartment',
 'LIG Flat',
 'Shri Balaji Apartment',
 'ANSALS DUPLEX FLAT',
 'Ansals API Esencia',
 'Sidhartha NCR One Phase 24.1 ★',
 'Bestech Park View Ananda',
 'Millenia',
 'Sanskriti Apartments',
 'M3M skywalk',
 'Laxmi Apartment sector 99A Gurgaon',
 'Ansal Estella',
 'Chanderlok Society',
 'ss residency',
 'Uphar lakshya homes',
 'Godrej Aria , sector 79 , Gurgaon',
 'M3M Woodshire',
 'Krishna appartment',
 'Spire Woods Now Ananda by Alpha corp']

In [8]:
df['price'].tolist()

['45 Lac',
 '50 Lac',
 '40 Lac',
 '1.47 Crore',
 '70 Lac',
 '41 Lac',
 '2 Crore',
 '1.8 Crore',
 '1.1 Crore',
 '4.75 Crore',
 '96 Lac',
 '29 Lac',
 '1.35 Crore',
 '95 Lac',
 '70 Lac',
 '3.95 Crore',
 '90 Lac',
 '1.05 Crore',
 nan,
 '2.2 Crore',
 '1.01 Crore',
 '1.85 Crore',
 '86 Lac',
 '1.85 Crore',
 '2.85 Crore',
 'Price on Request',
 '42 Lac',
 '6.15 Crore',
 '6.25 Crore',
 '42 Lac',
 '1.35 Crore',
 '1.6 Crore',
 '3.25 Crore',
 '45 Lac',
 '85 Lac',
 '75 Lac',
 '82 Lac',
 '1.8 Crore',
 '29.99 Lac',
 '78 Lac',
 '2 Crore',
 '74 Lac',
 '3.2 Crore',
 '1.3 Crore',
 '25 Lac',
 '95 Lac',
 '1.99 Crore',
 '1.05 Crore',
 '1.83 Crore',
 '2.25 Crore',
 '2.8 Crore',
 '1.6 Crore',
 '83 Lac',
 '83 Lac',
 '80 Lac',
 '1.25 Crore',
 '23 Lac',
 '30 Lac',
 '1.55 Crore',
 '79 Lac',
 '50 Lac',
 '1.01 Crore',
 '95 Lac',
 '99 Lac',
 '1.1 Crore',
 '1.9 Crore',
 '1 Crore',
 '2.5 Crore',
 '1.1 Crore',
 '29 Lac',
 '55 Lac',
 '65 Lac',
 '50 Lac',
 '31.75 Lac',
 '93 Lac',
 '1.2 Crore',
 '30 Lac',
 '56 Lac',
 '2.7 Crore',
 '1 Crore',
 '1.45 Crore',
 '1.25 Crore',
 '46 Lac',
 '4.5 Crore',
 '64 Lac',
 '28 Lac',
 '3.87 Crore',
 '1.38 Crore',
 '43 Lac',
 '28.5 Lac',
 '1.1 Crore',
 '2 Crore',
 '90 Lac',
 '90 Lac',
 '1.75 Crore',
 '93 Lac',
 '1.8 Crore',
 '2.1 Crore',
 '2 Crore',
 '2 Crore',
 '1.29 Crore',
 '2.85 Crore',
 '1.1 Crore',
 '1.65 Crore',
 '24 Lac',
 '2.1 Crore',
 '1.9 Crore',
 '1.1 Crore',
 '31.5 Lac',
 '1.7 Crore',
 '32 Lac',
 '45 Lac',
 '1.2 Crore',
 '2.1 Crore',
 '45 Lac',
 '42 Lac',
 '1.55 Crore',
 '1.3 Crore',
 '2.75 Crore',
 '1.25 Crore',
 '42 Lac',
 '40 Lac',
 '34 Lac',
 '1.25 Crore',
 '1.5 Crore',
 '1.3 Crore',
 '1.6 Crore',
 '1.5 Crore',
 '1.5 Crore',
 '90 Lac',
 '1.5 Crore',
 '80 Lac',
 '1.25 Crore',
 '26 Lac',
 '42 Lac',
 '2.5 Crore',
 '90 Lac',
 '42 Lac',
 '50 Lac',
 '90 Lac',
 '1.3 Crore',
 '1.7 Crore',
 '1.25 Crore',
 '2.91 Crore',
 '1.15 Crore',
 '1.2 Crore',
 '1.5 Crore',
 '1.3 Crore',
 '1.75 Crore',
 '55 Lac',
 '2.5 Crore',
 '43 Lac',
 '80 Lac',
 '45 Lac',
 '70 Lac',
 '1.95 Crore',
 '45 Lac',
 '1.7 Crore',
 '1.1 Crore',
 '50 Lac',
 '2.8 Crore',
 '1.45 Crore',
 '2.2 Crore',
 '90 Lac',
 '40 Lac',
 '1.35 Crore',
 '1.85 Crore',
 '25 Lac',
 '88 Lac',
 '1.15 Crore',
 '1.6 Crore',
 '85 Lac',
 '75 Lac',
 '3.35 Crore',
 '1.5 Crore',
 '1.65 Crore',
 '2 Crore',
 '1.75 Crore',
 '90 Lac',
 '1.25 Crore',
 '1 Crore',
 '1.08 Crore',
 '2.15 Crore',
 '1 Crore',
 '1.65 Crore',
 '1.79 Crore',
 '1.8 Crore',
 '1.45 Crore',
 '22 Lac',
 '36 Lac',
 '25 Lac',
 '1.15 Crore',
 '1.65 Crore',
 '2.9 Crore',
 '60 Lac',
 '2.4 Crore',
 '1.25 Crore',
 '2.15 Crore',
 '29.5 Lac',
 '38 Lac',
 '1.5 Crore',
 '39 Lac',
 '1.6 Crore',
 '1.7 Crore',
 '3.25 Crore',
 '60 Lac',
 '27 Lac',
 '95 Lac',
 '2.65 Crore',
 '36 Lac',
 '55 Lac',
 '1.32 Crore',
 '59 Lac',
 '45 Lac',
 '90 Lac',
 '1.4 Crore',
 '95 Lac',
 '3 Crore',
 '3.67 Crore',
 '3.85 Crore',
 '3.29 Crore',
 '2.33 Crore',
 '2.79 Crore',
 '3.4 Crore',
 '72 Lac',
 '40 Lac',
 '56 Lac',
 '1.1 Crore',
 '71 Lac',
 '78 Lac',
 '40 Lac',
 '1.85 Crore',
 '1.1 Crore',
 '1.41 Crore',
 '1.45 Crore',
 '2.2 Crore',
 '1.1 Crore',
 '2.05 Crore',
 '60 Lac',
 '80 Lac',
 '41 Lac',
 '90 Lac',
 '54 Lac',
 '82 Lac',
 '1 Crore',
 '1.85 Crore',
 '1.42 Crore',
 '55 Lac',
 '2.29 Crore',
 '97 Lac',
 '8.25 Crore',
 '30 Lac',
 '1.65 Crore',
 '1.99 Crore',
 '1 Crore',
 '4.25 Crore',
 '1.25 Crore',
 '95 Lac',
 '1.05 Crore',
 '4.1 Crore',
 '50 Lac',
 '1.65 Crore',
 '1.6 Crore',
 '2.1 Crore',
 '90 Lac',
 '1.1 Crore',
 '92 Lac',
 '70 Lac',
 '99 Lac',
 '71.5 Lac',
 '87.5 Lac',
 '91 Lac',
 '1.25 Crore',
 '1.05 Crore',
 '66 Lac',
 '1.83 Crore',
 '52.56 Lac',
 '80 Lac',
 '1.71 Crore',
 '65 Lac',
 '1.3 Crore',
 '82 Lac',
 '5.7 Crore',
 '88 Lac',
 '4 Crore',
 '1.93 Crore',
 '3.45 Crore',
 '1.7 Crore',
 '6.15 Crore',
 '1.4 Crore',
 '1.48 Crore',
 '3.25 Crore',
 '1.49 Crore',
 '30 Lac',
 '3.49 Crore',
 '2.15 Crore',
 '1.4 Crore',
 '2 Crore',
 '2.3 Crore',
 '54 Lac',
 '1.25 Crore',
 '1.05 Crore',
 '1.25 Crore',
 '1 Crore',
 '1.7 Crore',
 '1.3 Crore',
 '2.12 Crore',
 '3.9 Crore',
 '3 Crore',
 '2.2 Crore',
 '1.35 Crore',
 '1.67 Crore',
 '90 Lac',
 '2.37 Crore',
 '1.98 Crore',
 '3.7 Crore',
 '4.67 Crore',
 '1.29 Crore',
 '3.65 Crore',
 '1.7 Crore',
 '6.15 Crore',
 '1.4 Crore',
 '1.48 Crore',
 '3.49 Crore',
 '2.15 Crore',
 '2 Crore',
 '54 Lac',
 '1.25 Crore',
 '1.05 Crore',
 '1.25 Crore',
 '1 Crore',
 '1.7 Crore',
 '1.3 Crore',
 '2.12 Crore',
 '3 Crore',
 '1.35 Crore',
 '90 Lac',
 '1.98 Crore',
 '3.7 Crore',
 '1.29 Crore',
 '5.6 Crore',
 '1.25 Crore',
 '1.27 Crore',
 '1.36 Crore',
 '1 Crore',
 '4.25 Crore',
 '1.8 Crore',
 '1.25 Crore',
 '27 Lac',
 '5.5 Crore',
 '85 Lac',
 '1.07 Crore',
 '95 Lac',
 '87 Lac',
 '4.1 Crore',
 '1.27 Crore',
 '1.47 Crore',
 '3.45 Crore',
 '1.18 Crore',
 '1.55 Crore',
 '3.39 Crore',
 '1.54 Crore',
 '1.42 Crore',
 '1.3 Crore',
 '2.25 Crore',
 '3.5 Crore',
 '4.8 Crore',
 '78 Lac',
 '88 Lac',
 '2.6 Crore',
 '3.4 Crore',
 '2.9 Crore',
 '70 Lac',
 '1.5 Crore',
 '1.28 Crore',
 '2.51 Crore',
 '6.5 Crore',
 '3.63 Crore',
 '1.85 Crore',
 '2.45 Crore',
 '1.38 Crore',
 '5.9 Crore',
 '3 Crore',
 '2.01 Crore',
 '2.1 Crore',
 '4.25 Crore',
 '2.55 Crore',
 '2 Crore',
 '3.25 Crore',
 '1.6 Crore',
 '1.5 Crore',
 '3.75 Crore',
 '95 Lac',
 '1.4 Crore',
 '1.56 Crore',
 '1.35 Crore',
 '1.4 Crore',
 '2.26 Crore',
 '1.2 Crore',
 '2.08 Crore',
 '1.75 Crore',
 '2.99 Crore',
 '2.1 Crore',
 '2.87 Crore',
 '2.35 Crore',
 '3 Crore',
 '6 Crore',
 '2.35 Crore',
 '1.9 Crore',
 '72 Lac',
 '65 Lac',
 '2.34 Crore',
 '2.57 Crore',
 '1.71 Crore',
 '3.79 Crore',
 '2.05 Crore',
 '5.2 Crore',
 '3.2 Crore',
 '69 Lac',
 '3.75 Crore',
 '3.65 Crore',
 '5.49 Crore',
 '1.05 Crore',
 '3.35 Crore',
 '2.4 Crore',
 '1.71 Crore',
 '6.3 Crore',
 '2.2 Crore',
 '3.25 Crore',
 '11.25 Crore',
 '3.3 Crore',
 '1.51 Crore',
 '1.38 Crore',
 '4.6 Crore',
 '1.4 Crore',
 '3.5 Crore',
 '99 Lac',
 '2.65 Crore',
 '2.4 Crore',
 '1.65 Crore',
 '1.25 Crore',
 '4 Crore',
 '1.8 Crore',
 '1.75 Crore',
 '2.35 Crore',
 '7.15 Crore',
 '1.64 Crore',
 '2.8 Crore',
 '6.75 Crore',
 '3.5 Crore',
 '4.6 Crore',
 '2.25 Crore',
 '2.2 Crore',
 '2.85 Crore',
 '1.76 Crore',
 '1 Crore',
 '3.6 Crore',
 '1.78 Crore',
 '98 Lac',
 '2.82 Crore',
 '3.21 Crore',
 '1.9 Crore',
 '1.19 Crore',
 '1.35 Crore',
 '1.8 Crore',
 '1.35 Crore',
 '1.7 Crore',
 '1.6 Crore',
 '2.65 Crore',
 '54.99 Lac',
 '1.4 Crore',
 '1.26 Crore',
 '1.7 Crore',
 '4.1 Crore',
 '1.01 Crore',
 '1.45 Crore',
 '1.6 Crore',
 '2.99 Crore',
 '1.9 Crore',
 '1.75 Crore',
 '1.3 Crore',
 '2.95 Crore',
 '3.4 Crore',
 '3.32 Crore',
 '95 Lac',
 '1.55 Crore',
 '1.54 Crore',
 '2.45 Crore',
 '2.6 Crore',
 '1.83 Crore',
 '1.09 Crore',
 '1.87 Crore',
 '1.05 Crore',
 '1.77 Crore',
 '2.2 Crore',
 '60 Lac',
 '1.8 Crore',
 '64 Lac',
 '75 Lac',
 '4.95 Crore',
 '4.25 Crore',
 '5.31 Crore',
 '1.4 Crore',
 '2.8 Crore',
 '4.1 Crore',
 '3.4 Crore',
 '3.05 Crore',
 '4.25 Crore',
 '1.16 Crore',
 '3.55 Crore',
 '1.8 Crore',
 '1.75 Crore',
 '1.2 Crore',
 '1.52 Crore',
 '1.55 Crore',
 '2.4 Crore',
 '2.35 Crore',
 '2.28 Crore',
 '1.1 Crore',
 '2.3 Crore',
 '1.35 Crore',
 '2.45 Crore',
 '90 Lac',
 '2.8 Crore',
 '1.4 Crore',
 '1.36 Crore',
 '98.5 Lac',
 '56.2 Lac',
 '2.2 Crore',
 '1.2 Crore',
 '1.33 Crore',
 '87 Lac',
 '1.09 Crore',
 '3 Crore',
 '1.75 Crore',
 '1.75 Crore',
 '3.8 Crore',
 '3.5 Crore',
 '1.78 Crore',
 '1.08 Crore',
 '2.03 Crore',
 '1.12 Crore',
 '2 Crore',
 '1.04 Crore',
 '1.25 Crore',
 '2.05 Crore',
 '3.19 Crore',
 '3.85 Crore',
 '3.2 Crore',
 '88.5 Lac',
 '49 Lac',
 '1.65 Crore',
 '2.35 Crore',
 '1.4 Crore',
 '97 Lac',
 '2.35 Crore',
 '3.32 Crore',
 '1.25 Crore',
 '2.8 Crore',
 '4.7 Crore',
 '1.3 Crore',
 '62 Lac',
 '80 Lac',
 '1.73 Crore',
 '4.45 Crore',
 '2.3 Crore',
 '2.2 Crore',
 '2.12 Crore',
 '2.25 Crore',
 '1.9 Crore',
 '4.4 Crore',
 '1.75 Crore',
 '2.8 Crore',
 '4.63 Crore',
 '1.32 Crore',
 '1.16 Crore',
 '27 Lac',
 '27.75 Lac',
 '1.79 Crore',
 '1.55 Crore',
 '1.55 Crore',
 '3.35 Crore',
 '3.5 Crore',
 '4.8 Crore',
 '1.5 Crore',
 '2.78 Crore',
 '2.25 Crore',
 '2.55 Crore',
 '1.25 Crore',
 '85 Lac',
 '5.25 Crore',
 '1.3 Crore',
 '75 Lac',
 '3.65 Crore',
 '1.65 Crore',
 '1.25 Crore',
 '1.42 Crore',
 '1.27 Crore',
 '1.65 Crore',
 '1.24 Crore',
 '2.7 Crore',
 '1.98 Crore',
 '2.5 Crore',
 '2.29 Crore',
 '2.98 Crore',
 '1.35 Crore',
 '1.37 Crore',
 '1.55 Crore',
 '4.25 Crore',
 '1.28 Crore',
 '1.95 Crore',
 '2.35 Crore',
 '5 Crore',
 '99 Lac',
 '1.95 Crore',
 '3.3 Crore',
 '4.75 Crore',
 '1.5 Crore',
 '1.54 Crore',
 '1.27 Crore',
 '1.17 Crore',
 '1.8 Crore',
 '80 Lac',
 '1.76 Crore',
 '2.22 Crore',
 '1.24 Crore',
 '1.12 Crore',
 '1.9 Crore',
 '1.35 Crore',
 '2.22 Crore',
 '90 Lac',
 '1.75 Crore',
 '66.99 Lac',
 '2.95 Crore',
 '2.04 Crore',
 '2.24 Crore',
 '1.31 Crore',
 '1.7 Crore',
 '1.19 Crore',
 '1.75 Crore',
 '1.12 Crore',
 '92 Lac',
 '90 Lac',
 '2.3 Crore',
 '1.58 Crore',
 '4.25 Crore',
 '1.68 Crore',
 '4.55 Crore',
 '2.85 Crore',
 '2.35 Crore',
 '2.3 Crore',
 '2.26 Crore',
 '4.78 Crore',
 '2 Crore',
 '3.75 Crore',
 '6.16 Crore',
 '5.3 Crore',
 '75 Lac',
 '1.25 Crore',
 '2 Crore',
 '1.3 Crore',
 '1.75 Crore',
 '2 Crore',
 '1.78 Crore',
 '1.15 Crore',
 '1.65 Crore',
 '21 Lac',
 '2.75 Crore',
 '2.72 Crore',
 '2.4 Crore',
 '4.1 Crore',
 '1.12 Crore',
 '65 Lac',
 '7.5 Crore',
 '11 Crore',
 '1.26 Crore',
 '1.8 Crore',
 '5.9 Crore',
 '2.9 Crore',
 '1.59 Crore',
 '2.21 Crore',
 '1.48 Crore',
 '98 Lac',
 '2.04 Crore',
 '1.5 Crore',
 '1.49 Crore',
 '1.2 Crore',
 '86 Lac',
 '89.5 Lac',
 '2 Crore',
 '1.85 Crore',
 '2.65 Crore',
 '1.5 Crore',
 '1.75 Crore',
 '1.32 Crore',
 '80 Lac',
 '1.2 Crore',
 '6.5 Crore',
 '1.17 Crore',
 '1.15 Crore',
 '2.48 Crore',
 '1.35 Crore',
 '1.15 Crore',
 '2.95 Crore',
 '3.4 Crore',
 '2.8 Crore',
 '2.15 Crore',
 '1.76 Crore',
 '3.45 Crore',
 '3.3 Crore',
 '1.75 Crore',
 '2.78 Crore',
 '1.42 Crore',
 '2.4 Crore',
 '2.28 Crore',
 '1.9 Crore',
 '3.25 Crore',
 '1.6 Crore',
 '4.45 Crore',
 '82 Lac',
 '50 Lac',
 '52 Lac',
 '28 Lac',
 '29 Lac',
 '97 Lac',
 '80 Lac',
 '1.45 Crore',
 '55 Lac',
 '1.1 Crore',
 '1.4 Crore',
 '1.42 Crore',
 '2.95 Crore',
 '2.6 Crore',
 '1.1 Crore',
 '75 Lac',
 '1.3 Crore',
 '1.49 Crore',
 '1.19 Crore',
 '1.15 Crore',
 '99.5 Lac',
 '78 Lac',
 '1.15 Crore',
 '80 Lac',
 '2.2 Crore',
 '1.55 Crore',
 '1.55 Crore',
 '90 Lac',
 '90 Lac',
 '85 Lac',
 '3 Crore',
 '2.12 Crore',
 '1.05 Crore',
 '1.65 Crore',
 '1.5 Crore',
 '3.4 Crore',
 '3.5 Crore',
 '3.15 Crore',
 '5.25 Crore',
 '2.78 Crore',
 '72 Lac',
 '1.55 Crore',
 '1.5 Crore',
 '3.05 Crore',
 '3.83 Crore',
 '2.25 Crore',
 '1.4 Crore',
 '3.75 Crore',
 '1.51 Crore',
 '2.7 Crore',
 '3.35 Crore',
 '1.5 Crore',
 '2.2 Crore',
 '2.55 Crore',
 '45 Lac',
 '1.18 Crore',
 '85 Lac',
 '1.49 Crore',
 '6.5 Crore',
 '1.18 Crore',
 '80 Lac',
 '1.42 Crore',
 '5 Crore',
 '1.72 Crore',
 '1.95 Crore',
 '75 Lac',
 '1.72 Crore',
 '2.5 Crore',
 '1.7 Crore',
 '1.14 Crore',
 '1.35 Crore',
 '27.1 Lac',
 '1.4 Crore',
 '1.25 Crore',
 '1.18 Crore',
 '1.1 Crore',
 '1.21 Crore',
 '3.45 Crore',
 '1.95 Crore',
 '3.65 Crore',
 '2.3 Crore',
 '3.4 Crore',
 '1.14 Crore',
 '95.75 Lac',
 '3.05 Crore',
 '2.35 Crore',
 '1.05 Crore',
 '1.02 Crore',
 '1.08 Crore',
 '1.75 Crore',
 '2.45 Crore',
 '6 Crore',
 '1.68 Crore',
 '1.26 Crore',
 '1.82 Crore',
 '2.58 Crore',
 '1.75 Crore',
 '2.6 Crore',
 '2.9 Crore',
 '1.4 Crore',
 '2.95 Crore',
 '2.25 Crore',
 '1.4 Crore',
 '1.26 Crore',
 '1.7 Crore',
 '1.43 Crore',
 '1.3 Crore',
 '1.32 Crore',
 '2 Crore',
 '1.43 Crore',
 '3.46 Crore',
 '2.25 Crore',
 '1.7 Crore',
 '1.8 Crore',
 '1.35 Crore',
 '5.4 Crore',
 '1.55 Crore',
 '1.6 Crore',
 '2.09 Crore',
 '1.75 Crore',
 '1.38 Crore',
 '2.25 Crore',
 '2.4 Crore',
 '1.72 Crore',
 '88 Lac',
 '3.15 Crore',
 '1.72 Crore',
 '1.47 Crore',
 '1.1 Crore',
 '1.32 Crore',
 '1.3 Crore',
 '1.35 Crore',
 '3 Crore',
 '1.6 Crore',
 '3 Crore',
 '90 Lac',
 '1.75 Crore',
 '2 Crore',
 '1.8 Crore',
 '1.6 Crore',
 '1.4 Crore',
 '1.8 Crore',
 '2.7 Crore',
 '1.55 Crore',
 '1.15 Crore',
 '1.49 Crore',
 '1.91 Crore',
 '1.05 Crore',
 '2.14 Crore',
 '1.02 Crore',
 '55.6 Lac',
 '2.5 Crore',
 '2 Crore',
 '2.2 Crore',
 '1.65 Crore',
 '1.6 Crore',
 '85 Lac',
 '1.4 Crore',
 '2.09 Crore',
 '2.51 Crore',
 '1.69 Crore',
 '98.1 Lac',
 '2 Crore',
 '1.95 Crore',
 '2.1 Crore',
 '1.55 Crore',
 '1.98 Crore',
 '2.05 Crore',
 '1.4 Crore',
 '1.4 Crore',
 '2.36 Crore',
 '1.65 Crore',
 '2.65 Crore',
 '2.63 Crore',
 '2.25 Crore',
 '2.55 Crore',
 '1.15 Crore',
 '1.45 Crore',
 '2.6 Crore',
 '1.55 Crore',
 '1.2 Crore',
 '1.55 Crore',
 '1.65 Crore',
 '1.05 Crore',
 '1.29 Crore',
 '55.5 Lac',
 '1.26 Crore',
 '1.91 Crore',
 '2.2 Crore',
 '1.98 Crore',
 '1.11 Crore',
 '2.25 Crore',
 '1.05 Crore',
 '2.6 Crore',
 '1.04 Crore',
 '1.25 Crore',
 '3.4 Crore',
 '1.25 Crore',
 '41.5 Lac',
 '75 Lac',
 '1.7 Crore',
 '87 Lac',
 '1.25 Crore',
 '2.35 Crore',
 '1.73 Crore',
 '97 Lac',
 '1.35 Crore',
 '1.32 Crore',
 '71.5 Lac',
 '78 Lac',
 '5.5 Crore',
 '2.3 Crore',
 '43 Lac',
 '98.5 Lac',
 '80 Lac',
 '2.65 Crore',
 '2.35 Crore',
 '1.29 Crore',
 '1.83 Crore',
 '1.39 Crore',
 '1.12 Crore',
 '65 Lac',
 '1.5 Crore',
 '1.9 Crore',
 '2.35 Crore',
 '60 Lac',
 '2 Crore',
 '1.57 Crore',
 '1.44 Crore',
 '1.26 Crore',
 '1.05 Crore',
 '6.44 Crore',
 '7.56 Crore',
 '3.8 Crore',
 '6.75 Crore',
 '64.5 Lac',
 '1.75 Crore',
 '1.54 Crore',
 '1.4 Crore',
 '97 Lac',
 '1.35 Crore',
 '1.75 Crore',
 '2.2 Crore',
 '2.45 Crore',
 '1.5 Crore',
 '2.4 Crore',
 '2.45 Crore',
 '3 Crore',
 '1.65 Crore',
 '88 Lac',
 '88 Lac',
 '1.28 Crore',
 '1.34 Crore',
 '1.32 Crore',
 '1.13 Crore',
 '1.38 Crore',
 '1.16 Crore',
 '2.33 Crore',
 '3.05 Crore',
 '1.25 Crore',
 '1.25 Crore',
 '1.05 Crore',
 '1.25 Crore',
 '1.1 Crore',
 '1.3 Crore',
 '2.28 Crore',
 '1.2 Crore',
 '1.22 Crore',
 '1.1 Crore',
 '1.15 Crore',
 '1.2 Crore',
 '1.4 Crore',
 '1.1 Crore',
 '1 Crore',
 '1.52 Crore',
 '1.8 Crore',
 '1.6 Crore',
 '1.55 Crore',
 '1.3 Crore',
 '2.25 Crore',
 '4.79 Crore',
 ...]

In [9]:
df['bathroom'].tolist()

['2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '1 Bathroom',
 '1 Bathroom',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '1 Bathroom',
 '5 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '1 Bathroom',
 '5 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '6 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '6 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '7 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '2 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '1 Bathroom',
 '3 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '6 Bathrooms',
 '3 Bathrooms',
 '6 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '5 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '2 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '3 Bathrooms',
 '4 Bathrooms',
 '5 Bathrooms',
 ...]

In [10]:
df['balcony'].tolist()

['1 Balcony',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 'No Balcony',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 'No Balcony',
 '1 Balcony',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 'No Balcony',
 '2 Balconies',
 '3+ Balconies',
 '1 Balcony',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '1 Balcony',
 '1 Balcony',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 'No Balcony',
 '1 Balcony',
 '3+ Balconies',
 '1 Balcony',
 '1 Balcony',
 '3+ Balconies',
 '1 Balcony',
 '1 Balcony',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 'No Balcony',
 'No Balcony',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '1 Balcony',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '1 Balcony',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 'No Balcony',
 '3 Balconies',
 'No Balcony',
 '1 Balcony',
 '1 Balcony',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '1 Balcony',
 '1 Balcony',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 'No Balcony',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '1 Balcony',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 'No Balcony',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 'No Balcony',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '1 Balcony',
 '1 Balcony',
 '3+ Balconies',
 'No Balcony',
 '3+ Balconies',
 '3 Balconies',
 'No Balcony',
 '3 Balconies',
 '3+ Balconies',
 '1 Balcony',
 '2 Balconies',
 '3 Balconies',
 '1 Balcony',
 'No Balcony',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 'No Balcony',
 '1 Balcony',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '1 Balcony',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '1 Balcony',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 'No Balcony',
 '2 Balconies',
 '3 Balconies',
 'No Balcony',
 'No Balcony',
 'No Balcony',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '1 Balcony',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '1 Balcony',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '1 Balcony',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '1 Balcony',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '1 Balcony',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '1 Balcony',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3+ Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '1 Balcony',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3 Balconies',
 '2 Balconies',
 '2 Balconies',
 '3 Balconies',
 '3 Balconies',
 '3+ Balconies',
 '3 Balconies',
 '2 Balconies',
 '3+ Balconies',
 '3+ Balconies',
 ...]

In [11]:
df['areaWithType'].unique().tolist()

['Carpet area: 900 (83.61 sq.m.)',
 'Carpet area: 650 (60.39 sq.m.)',
 'Carpet area: 595 (55.28 sq.m.)',
 'Carpet area: 1200 (111.48 sq.m.)',
 'Super Built up area 1345(124.95 sq.m.)',
 'Built Up area: 654 (60.76 sq.m.)',
 'Super Built up area 1500(139.35 sq.m.)',
 'Carpet area: 2290 (212.75 sq.m.)',
 'Built Up area: 1350 (125.42 sq.m.)Carpet area: 1050 sq.ft. (97.55 sq.m.)',
 'Built Up area: 2813 (261.34 sq.m.)',
 'Carpet area: 1075 (99.87 sq.m.)',
 'Carpet area: 519 (48.22 sq.m.)',
 'Carpet area: 1945 (180.7 sq.m.)',
 'Super Built up area 1385(128.67 sq.m.)',
 'Super Built up area 1300(120.77 sq.m.)',
 'Built Up area: 2343 (217.67 sq.m.)Carpet area: 2300 sq.ft. (213.68 sq.m.)',
 'Built Up area: 639 (59.37 sq.m.)',
 'Carpet area: 915 (85.01 sq.m.)',
 'Carpet area: 577.11 (53.62 sq.m.)',
 'Super Built up area 2100(195.1 sq.m.)',
 'Carpet area: 1103 (102.47 sq.m.)',
 'Super Built up area 2150(199.74 sq.m.)',
 'Super Built up area 1103(102.47 sq.m.)',
 'Carpet area: 2025 (188.13 sq.m.)',
 'Super Built up area 2217(205.97 sq.m.)',
 'Built Up area: 4500 (418.06 sq.m.)',
 'Carpet area: 531 (49.33 sq.m.)',
 'Built Up area: 3355 (311.69 sq.m.)Carpet area: 2200 sq.ft. (204.39 sq.m.)',
 'Carpet area: 2880 (267.56 sq.m.)',
 'Carpet area: 750 (69.68 sq.m.)',
 'Built Up area: 1056 (98.11 sq.m.)Carpet area: 912 sq.ft. (84.73 sq.m.)',
 'Carpet area: 66 (55.18 sq.m.)',
 'Super Built up area 3200(297.29 sq.m.)Carpet area: 3000 sq.ft. (278.71 sq.m.)',
 'Carpet area: 625.47 (58.11 sq.m.)',
 'Built Up area: 1300 (120.77 sq.m.)',
 'Carpet area: 1300 (120.77 sq.m.)',
 'Super Built up area 1180(109.63 sq.m.)',
 'Super Built up area 2030(188.59 sq.m.)Carpet area: 1785 sq.ft. (165.83 sq.m.)',
 'Super Built up area 655(60.85 sq.m.)Carpet area: 555 sq.ft. (51.56 sq.m.)',
 'Super Built up area 1365(126.81 sq.m.)Built Up area: 1068.1 sq.ft. (99.23 sq.m.)Carpet area: 900 sq.ft. (83.61 sq.m.)',
 'Carpet area: 1320 (122.63 sq.m.)',
 'Carpet area: 1210 (112.41 sq.m.)',
 'Carpet area: 2002 (185.99 sq.m.)',
 'Super Built up area 1960(182.09 sq.m.)',
 'Carpet area: 700 (65.03 sq.m.)',
 'Built Up area: 1210.73 (112.48 sq.m.)Carpet area: 756.6 sq.ft. (70.29 sq.m.)',
 'Carpet area: 2727 (253.35 sq.m.)',
 'Carpet area: 1385 (128.67 sq.m.)',
 'Carpet area: 1829 (169.92 sq.m.)',
 'Carpet area: 2100 (195.1 sq.m.)',
 'Carpet area: 1650 (153.29 sq.m.)',
 'Carpet area: 1100 (102.19 sq.m.)',
 'Carpet area: 1530 (142.14 sq.m.)',
 'Carpet area: 1120 (104.05 sq.m.)',
 'Carpet area: 1250 (116.13 sq.m.)',
 'Carpet area: 2651 (246.29 sq.m.)',
 'Carpet area: 460 (42.74 sq.m.)',
 'Carpet area: 450 (41.81 sq.m.)',
 'Super Built up area 1570(145.86 sq.m.)',
 'Super Built up area 1198(111.3 sq.m.)',
 'Super Built up area 900(83.61 sq.m.)Carpet area: 750 sq.ft. (69.68 sq.m.)',
 'Super Built up area 1450(134.71 sq.m.)Carpet area: 950 sq.ft. (88.26 sq.m.)',
 'Super Built up area 1897(176.24 sq.m.)',
 'Super Built up area 1260(117.06 sq.m.)Carpet area: 1000 sq.ft. (92.9 sq.m.)',
 'Super Built up area 1725(160.26 sq.m.)',
 'Super Built up area 2200(204.39 sq.m.)',
 'Super Built up area 1875(174.19 sq.m.)',
 'Super Built up area 2250(209.03 sq.m.)',
 'Super Built up area 1056.58(98.16 sq.m.)',
 'Super Built up area 560(52.03 sq.m.)',
 'Built Up area: 990 (91.97 sq.m.)Carpet area: 950 sq.ft. (88.26 sq.m.)',
 'Super Built up area 1370(127.28 sq.m.)',
 'Carpet area: 531.57 (49.38 sq.m.)',
 'Super Built up area 575(53.42 sq.m.)Carpet area: 570.17 sq.ft. (52.97 sq.m.)',
 'Carpet area: 1452 (134.9 sq.m.)',
 'Carpet area: 1423 (132.2 sq.m.)',
 'Carpet area: 640 (59.46 sq.m.)',
 'Carpet area: 822 (76.37 sq.m.)',
 'Super Built up area 2159(200.58 sq.m.)',
 'Super Built up area 1950(181.16 sq.m.)',
 'Built Up area: 1300 (120.77 sq.m.)Carpet area: 1090 sq.ft. (101.26 sq.m.)',
 'Built Up area: 1423 (132.2 sq.m.)Carpet area: 1190 sq.ft. (110.55 sq.m.)',
 'Carpet area: 58141 (5401.48 sq.m.)',
 'Super Built up area 3670(340.95 sq.m.)',
 'Super Built up area 1000(92.9 sq.m.)',
 'Built Up area: 743 (69.03 sq.m.)Carpet area: 643 sq.ft. (59.74 sq.m.)',
 'Super Built up area 2250(209.03 sq.m.)Carpet area: 1249.65 sq.ft. (116.1 sq.m.)',
 'Carpet area: 2177 (202.25 sq.m.)',
 'Carpet area: 1118 (103.87 sq.m.)',
 'Built Up area: 1433 (133.13 sq.m.)Carpet area: 1000 sq.ft. (92.9 sq.m.)',
 'Super Built up area 1120(104.05 sq.m.)',
 'Built Up area: 1120 (104.05 sq.m.)',
 'Built Up area: 1996 (185.43 sq.m.)',
 'Carpet area: 1080 (100.34 sq.m.)',
 'Super Built up area 2727(253.35 sq.m.)',
 'Super Built up area 1789(166.2 sq.m.)',
 'Carpet area: 1380 (128.21 sq.m.)',
 'Built Up area: 1540 (143.07 sq.m.)',
 'Super Built up area 1629(151.34 sq.m.)Carpet area: 1628 sq.ft. (151.25 sq.m.)',
 'Super Built up area 1828(169.83 sq.m.)',
 'Carpet area: 1950 (181.16 sq.m.)',
 'Carpet area: 324 (30.1 sq.m.)',
 'Super Built up area 2000(185.81 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1500 sq.ft. (139.35 sq.m.)',
 'Carpet area: 1929 (179.21 sq.m.)',
 'Super Built up area 89',
 'Super Built up area 700(65.03 sq.m.)Carpet area: 443.32 sq.ft. (41.19 sq.m.)',
 'Built Up area: 965 (89.65 sq.m.)Carpet area: 628 sq.ft. (58.34 sq.m.)',
 'Super Built up area 524(48.68 sq.m.)Carpet area: 424.8 sq.ft. (39.47 sq.m.)',
 'Carpet area: 581.41 (54.01 sq.m.)',
 'Super Built up area 1197.8(111.28 sq.m.)Carpet area: 505 sq.ft. (46.92 sq.m.)',
 'Super Built up area 1310(121.7 sq.m.)',
 'Carpet area: 569243 (52884.41 sq.m.)',
 'Carpet area: 1557 (144.65 sq.m.)',
 'Super Built up area 1440(133.78 sq.m.)',
 'Carpet area: 2597 (241.27 sq.m.)',
 'Super Built up area 1940(180.23 sq.m.)Carpet area: 1056 sq.ft. (98.11 sq.m.)',
 'Carpet area: 567 (52.68 sq.m.)',
 'Super Built up area 623(57.88 sq.m.)Carpet area: 599 sq.ft. (55.65 sq.m.)',
 'Carpet area: 629 (58.44 sq.m.)',
 'Super Built up area 1423(132.2 sq.m.)',
 'Super Built up area 1450(134.71 sq.m.)Carpet area: 1177 sq.ft. (109.35 sq.m.)',
 'Super Built up area 1400(130.06 sq.m.)',
 'Super Built up area 2000(185.81 sq.m.)',
 'Carpet area: 1276 (118.54 sq.m.)',
 'Super Built up area 1276(118.54 sq.m.)',
 'Built Up area: 1259 (116.96 sq.m.)',
 'Super Built up area 1640(152.36 sq.m.)',
 'Built Up area: 610 (56.67 sq.m.)',
 'Super Built up area 1690(157.01 sq.m.)',
 'Carpet area: 481.74 (44.76 sq.m.)',
 'Super Built up area 215(179.77 sq.m.)',
 'Super Built up area 1950(181.16 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1854 sq.ft. (172.24 sq.m.)',
 'Carpet area: 591 (54.91 sq.m.)',
 'Super Built up area 546(50.73 sq.m.)',
 'Super Built up area 1530(142.14 sq.m.)Built Up area: 1450 sq.ft. (134.71 sq.m.)Carpet area: 1400 sq.ft. (130.06 sq.m.)',
 'Carpet area: 1910 (177.44 sq.m.)',
 'Built Up area: 2040 (189.52 sq.m.)',
 'Super Built up area 4350(404.13 sq.m.)Carpet area: 3480 sq.ft. (323.3 sq.m.)',
 'Super Built up area 2500(232.26 sq.m.)Built Up area: 2000 sq.ft. (185.81 sq.m.)Carpet area: 1750 sq.ft. (162.58 sq.m.)',
 'Carpet area: 958 (89 sq.m.)',
 'Carpet area: 1225 (113.81 sq.m.)',
 'Super Built up area 1751(162.67 sq.m.)Carpet area: 1290 sq.ft. (119.84 sq.m.)',
 'Super Built up area 1689(156.91 sq.m.)',
 'Super Built up area 810(75.25 sq.m.)',
 'Built Up area: 1440 (133.78 sq.m.)Carpet area: 1080 sq.ft. (100.34 sq.m.)',
 'Built Up area: 1468 (136.38 sq.m.)Carpet area: 1150 sq.ft. (106.84 sq.m.)',
 'Super Built up area 2191(203.55 sq.m.)Built Up area: 1650 sq.ft. (153.29 sq.m.)Carpet area: 1350 sq.ft. (125.42 sq.m.)',
 'Carpet area: 626 (58.16 sq.m.)',
 'Built Up area: 1570 (145.86 sq.m.)Carpet area: 1099 sq.ft. (102.1 sq.m.)',
 'Carpet area: 1800 (167.23 sq.m.)',
 'Carpet area: 520 (48.31 sq.m.)',
 'Built Up area: 118 Carpet area: 86 sq.m.',
 'Carpet area: 1630 (151.43 sq.m.)',
 'Super Built up area 1275(118.45 sq.m.)Carpet area: 951 sq.ft. (88.35 sq.m.)',
 'Carpet area: 514 (47.75 sq.m.)',
 'Super Built up area 1735(161.19 sq.m.)Carpet area: 1199 sq.ft. (111.39 sq.m.)',
 'Carpet area: 2300 (213.68 sq.m.)',
 'Super Built up area 380(35.3 sq.m.)',
 'Carpet area: 1105 (102.66 sq.m.)',
 'Super Built up area 1365(126.81 sq.m.)',
 'Super Built up area 1313(121.98 sq.m.)',
 'Super Built up area 1252(116.31 sq.m.)',
 'Built Up area: 1000 (92.9 sq.m.)Carpet area: 650 sq.ft. (60.39 sq.m.)',
 'Carpet area: 4500 (418.06 sq.m.)',
 'Super Built up area 1850(171.87 sq.m.)',
 'Super Built up area 2364(219.62 sq.m.)',
 'Carpet area: 2800 (260.13 sq.m.)',
 'Carpet area: 1180 (109.63 sq.m.)',
 'Super Built up area 1865(173.26 sq.m.)',
 'Carpet area: 1537 (142.79 sq.m.)',
 'Built Up area: 1758 (163.32 sq.m.)',
 'Super Built up area 2408(223.71 sq.m.)',
 'Built Up area: 826 (76.74 sq.m.)',
 'Super Built up area 1262(117.24 sq.m.)',
 'Carpet area: 2215 (205.78 sq.m.)',
 'Carpet area: 127.3',
 'Built Up area: 1430 (132.85 sq.m.)Carpet area: 760 sq.ft. (70.61 sq.m.)',
 'Super Built up area 585(54.35 sq.m.)Carpet area: 465 sq.ft. (43.2 sq.m.)',
 'Built Up area: 700 (65.03 sq.m.)',
 'Built Up area: 587 (54.53 sq.m.)',
 'Super Built up area 1534(142.51 sq.m.)Built Up area: 1200 sq.ft. (111.48 sq.m.)Carpet area: 1103 sq.ft. (102.47 sq.m.)',
 'Carpet area: 946 (87.89 sq.m.)',
 'Carpet area: 2298 (213.49 sq.m.)',
 'Super Built up area 1320(122.63 sq.m.)',
 'Carpet area: 2400 (222.97 sq.m.)',
 'Carpet area: 1262 (117.24 sq.m.)',
 'Built Up area: 1433 (133.13 sq.m.)',
 'Built Up area: 743 (69.03 sq.m.)Carpet area: 519 sq.ft. (48.22 sq.m.)',
 'Built Up area: 750 (69.68 sq.m.)Carpet area: 650 sq.ft. (60.39 sq.m.)',
 'Built Up area: 1200 (111.48 sq.m.)Carpet area: 1100 sq.ft. (102.19 sq.m.)',
 'Built Up area: 950 (88.26 sq.m.)Carpet area: 750 sq.ft. (69.68 sq.m.)',
 'Built Up area: 2400 (222.97 sq.m.)',
 'Super Built up area 1999(185.71 sq.m.)',
 'Carpet area: 2302 (213.86 sq.m.)',
 'Carpet area: 710 (65.96 sq.m.)',
 'Super Built up area 1000(92.9 sq.m.)Carpet area: 550 sq.ft. (51.1 sq.m.)',
 'Carpet area: 1069 (99.31 sq.m.)',
 'Super Built up area 1433(133.13 sq.m.)',
 'Built Up area: 546 (50.73 sq.m.)Carpet area: 471 sq.ft. (43.76 sq.m.)',
 'Super Built up area 600(55.74 sq.m.)',
 'Carpet area: 780 (72.46 sq.m.)',
 'Super Built up area 1252.13(116.33 sq.m.)',
 'Carpet area: 850 (78.97 sq.m.)',
 'Super Built up area 1285(119.38 sq.m.)Built Up area: 1185 sq.ft. (110.09 sq.m.)Carpet area: 975 sq.ft. (90.58 sq.m.)',
 'Carpet area: 1400 (130.06 sq.m.)',
 'Super Built up area 1452(134.9 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)',
 'Super Built up area 2040(189.52 sq.m.)',
 'Carpet area: 5140 (477.52 sq.m.)',
 'Super Built up area 1261(117.15 sq.m.)',
 'Built Up area: 2900 (269.42 sq.m.)',
 'Carpet area: 990 (91.97 sq.m.)',
 'Super Built up area 568.46(52.81 sq.m.)',
 'Super Built up area 1364(126.72 sq.m.)',
 'Super Built up area 1620(150.5 sq.m.)',
 'Super Built up area 1310(121.7 sq.m.)Built Up area: 1100 sq.ft. (102.19 sq.m.)Carpet area: 1000 sq.ft. (92.9 sq.m.)',
 'Super Built up area 1295(120.31 sq.m.)',
 'Carpet area: 680 (63.17 sq.m.)',
 'Super Built up area 1579(146.69 sq.m.)',
 'Super Built up area 903(83.89 sq.m.)',
 'Built Up area: 1150 (106.84 sq.m.)',
 'Carpet area: 1600 (148.64 sq.m.)',
 'Super Built up area 1110(103.12 sq.m.)Built Up area: 1100 sq.ft. (102.19 sq.m.)Carpet area: 1000 sq.ft. (92.9 sq.m.)',
 'Super Built up area 1660(154.22 sq.m.)',
 'Super Built up area 583(54.16 sq.m.)Built Up area: 565 sq.ft. (52.49 sq.m.)Carpet area: 483 sq.ft. (44.87 sq.m.)',
 'Built Up area: 1622 (150.69 sq.m.)',
 'Super Built up area 1081(100.43 sq.m.)Carpet area: 650 sq.ft. (60.39 sq.m.)',
 'Super Built up area 1485(137.96 sq.m.)',
 'Carpet area: 2050 (190.45 sq.m.)',
 'Carpet area: 1775 (164.9 sq.m.)',
 'Super Built up area 850(78.97 sq.m.)Built Up area: 610 sq.ft. (56.67 sq.m.)Carpet area: 600 sq.ft. (55.74 sq.m.)',
 'Carpet area: 1433 (133.13 sq.m.)',
 'Super Built up area 915(85.01 sq.m.)Carpet area: 600 sq.ft. (55.74 sq.m.)',
 'Super Built up area 2940(273.13 sq.m.)',
 'Carpet area: 675 (62.71 sq.m.)',
 'Carpet area: 1151 (106.93 sq.m.)',
 'Super Built up area 1260(117.06 sq.m.)',
 'Carpet area: 800 (74.32 sq.m.)',
 'Super Built up area 2350(218.32 sq.m.)Built Up area: 2300 sq.ft. (213.68 sq.m.)Carpet area: 2000 sq.ft. (185.81 sq.m.)',
 'Carpet area: 1340 (124.49 sq.m.)',
 'Carpet area: 1350 (125.42 sq.m.)',
 'Super Built up area 2905(269.88 sq.m.)',
 'Carpet area: 716 (66.52 sq.m.)',
 'Carpet area: 1575 (146.32 sq.m.)',
 'Super Built up area 1549(143.91 sq.m.)Carpet area: 1500 sq.ft. (139.35 sq.m.)',
 'Super Built up area 2467(229.19 sq.m.)',
 'Super Built up area 1351(125.51 sq.m.)',
 'Built Up area: 140 (117.06 sq.m.)',
 'Super Built up area 1565(145.39 sq.m.)',
 'Super Built up area 1295(120.31 sq.m.)Carpet area: 1250 sq.ft. (116.13 sq.m.)',
 'Super Built up area 1361(126.44 sq.m.)',
 'Carpet area: 1326 (123.19 sq.m.)',
 'Carpet area: 997 (92.62 sq.m.)',
 'Built Up area: 1310 (121.7 sq.m.)',
 'Super Built up area 1095(101.73 sq.m.)',
 'Super Built up area 1380(128.21 sq.m.)Built Up area: 1300 sq.ft. (120.77 sq.m.)Carpet area: 1200 sq.ft. (111.48 sq.m.)',
 'Built Up area: 1423 (132.2 sq.m.)',
 'Built Up area: 1997 (185.53 sq.m.)',
 'Built Up area: 1523 (141.49 sq.m.)',
 'Built Up area: 1382 (128.39 sq.m.)',
 'Built Up area: 804 (74.69 sq.m.)Carpet area: 600 sq.ft. (55.74 sq.m.)',
 'Built Up area: 3350 (311.23 sq.m.)',
 'Super Built up area 2408(223.71 sq.m.)Built Up area: 2400 sq.ft. (222.97 sq.m.)Carpet area: 2390 sq.ft. (222.04 sq.m.)',
 'Super Built up area 2600(241.55 sq.m.)',
 'Built Up area: 2200 (204.39 sq.m.)Carpet area: 1610 sq.ft. (149.57 sq.m.)',
 'Carpet area: 3844 (357.12 sq.m.)',
 'Super Built up area 1780(165.37 sq.m.)',
 'Super Built up area 2000(185.81 sq.m.)Carpet area: 1294 sq.ft. (120.22 sq.m.)',
 'Carpet area: 4328 (402.08 sq.m.)',
 'Carpet area: 1750 (162.58 sq.m.)',
 'Carpet area: 761 (70.7 sq.m.)',
 'Carpet area: 2452 (227.8 sq.m.)',
 'Carpet area: 1508 (140.1 sq.m.)',
 'Super Built up area 1500(139.35 sq.m.)Carpet area: 1385 sq.ft. (128.67 sq.m.)',
 'Super Built up area 1407(130.71 sq.m.)',
 'Super Built up area 1630(151.43 sq.m.)',
 'Carpet area: 745 (69.21 sq.m.)',
 'Carpet area: 1806 (167.78 sq.m.)',
 'Built Up area: 97 Carpet area: 92 sq.m.',
 'Carpet area: 1450 (134.71 sq.m.)',
 'Super Built up area 1100(102.19 sq.m.)',
 'Super Built up area 2786(258.83 sq.m.)',
 'Built Up area: 1852 (172.06 sq.m.)Carpet area: 1250 sq.ft. (116.13 sq.m.)',
 'Carpet area: 1249.65 (116.1 sq.m.)',
 'Super Built up area 2605(242.01 sq.m.)',
 'Carpet area: 1549 (143.91 sq.m.)',
 'Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)',
 'Carpet area: 1671 (155.24 sq.m.)',
 'Super Built up area 1350(125.42 sq.m.)',
 'Built Up area: 2060 (191.38 sq.m.)Carpet area: 1600 sq.ft. (148.64 sq.m.)',
 'Carpet area: 2000 (185.81 sq.m.)',
 'Carpet area: 2750 (255.48 sq.m.)',
 'Super Built up area 1572(146.04 sq.m.)',
 'Super Built up area 1870(173.73 sq.m.)Built Up area: 1869 sq.ft. (173.64 sq.m.)',
 'Super Built up area 2892(268.68 sq.m.)',
 'Super Built up area 2143(199.09 sq.m.)',
 'Carpet area: 1304 (121.15 sq.m.)',
 'Super Built up area 1758(163.32 sq.m.)Carpet area: 986 sq.ft. (91.6 sq.m.)',
 'Built Up area: 1250 (116.13 sq.m.)Carpet area: 915 sq.ft. (85.01 sq.m.)',
 'Super Built up area 4553(422.99 sq.m.)',
 'Super Built up area 1900(176.52 sq.m.)',
 'Super Built up area 1743(161.93 sq.m.)',
 'Carpet area: 457.81 (42.53 sq.m.)',
 'Super Built up area 3025(281.03 sq.m.)',
 'Super Built up area 1990(184.88 sq.m.)',
 'Super Built up area 1283(119.19 sq.m.)Built Up area: 978.23 sq.ft. (90.88 sq.m.)Carpet area: 734.43 sq.ft. (68.23 sq.m.)',
 'Super Built up area 2344(217.76 sq.m.)Built Up area: 2343 sq.ft. (217.67 sq.m.)Carpet area: 1752 sq.ft. (162.77 sq.m.)',
 'Super Built up area 1383(128.48 sq.m.)',
 'Carpet area: 1150 (106.84 sq.m.)',
 'Super Built up area 2200(204.39 sq.m.)Built Up area: 2000 sq.ft. (185.81 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)',
 'Super Built up area 1920(178.37 sq.m.)',
 'Super Built up area 2358(219.07 sq.m.)Built Up area: 2100 sq.ft. (195.1 sq.m.)Carpet area: 2000 sq.ft. (185.81 sq.m.)',
 'Super Built up area 1929(179.21 sq.m.)Built Up area: 1780 sq.ft. (165.37 sq.m.)Carpet area: 1670 sq.ft. (155.15 sq.m.)',
 'Super Built up area 1500(139.35 sq.m.)Carpet area: 1300 sq.ft. (120.77 sq.m.)',
 'Super Built up area 1777(165.09 sq.m.)Built Up area: 1700 sq.ft. (157.94 sq.m.)Carpet area: 1550 sq.ft. (144 sq.m.)',
 'Super Built up area 2698(250.65 sq.m.)Built Up area: 2490 sq.ft. (231.33 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)',
 'Carpet area: 2500 (232.26 sq.m.)',
 'Super Built up area 1197(111.2 sq.m.)',
 'Super Built up area 1800(167.23 sq.m.)Carpet area: 1123 sq.ft. (104.33 sq.m.)',
 'Super Built up area 2598(241.36 sq.m.)',
 'Carpet area: 2470 (229.47 sq.m.)',
 'Super Built up area 2003(186.08 sq.m.)',
 'Super Built up area 1505(139.82 sq.m.)',
 'Super Built up area 1929(179.21 sq.m.)Built Up area: 1780 sq.ft. (165.37 sq.m.)Carpet area: 1540 sq.ft. (143.07 sq.m.)',
 'Super Built up area 1695(157.47 sq.m.)',
 'Carpet area: 3500 (325.16 sq.m.)',
 'Super Built up area 2150(199.74 sq.m.)Built Up area: 1650 sq.ft. (153.29 sq.m.)Carpet area: 1350 sq.ft. (125.42 sq.m.)',
 'Super Built up area 2875(267.1 sq.m.)',
 'Super Built up area 2120(196.95 sq.m.)Built Up area: 1616 sq.ft. (150.13 sq.m.)',
 'Super Built up area 5350(497.03 sq.m.)',
 'Super Built up area 4890(454.3 sq.m.)',
 'Carpet area: 1760 (163.51 sq.m.)',
 'Carpet area: 1759 (163.42 sq.m.)',
 'Super Built up area 3200(297.29 sq.m.)Carpet area: 3156 sq.ft. (293.2 sq.m.)',
 'Super Built up area 2070(192.31 sq.m.)Built Up area: 2060 sq.ft. (191.38 sq.m.)Carpet area: 1760 sq.ft. (163.51 sq.m.)',
 'Super Built up area 2350(218.32 sq.m.)Carpet area: 1850 sq.ft. (171.87 sq.m.)',
 'Carpet area: 2537 (235.7 sq.m.)',
 'Super Built up area 2343(217.67 sq.m.)',
 'Carpet area: 1416 (131.55 sq.m.)',
 'Super Built up area 1929(179.21 sq.m.)Built Up area: 1580 sq.ft. (146.79 sq.m.)Carpet area: 1450 sq.ft. (134.71 sq.m.)',
 'Super Built up area 1349(125.33 sq.m.)Carpet area: 1000 sq.ft. (92.9 sq.m.)',
 'Super Built up area 1777(165.09 sq.m.)Built Up area: 1700 sq.ft. (157.94 sq.m.)Carpet area: 1650 sq.ft. (153.29 sq.m.)',
 'Built Up area: 1492 (138.61 sq.m.)Carpet area: 900 sq.ft. (83.61 sq.m.)',
 'Super Built up area 2443(226.96 sq.m.)',
 'Super Built up area 2527(234.77 sq.m.)Built Up area: 2200 sq.ft. (204.39 sq.m.)Carpet area: 2100 sq.ft. (195.1 sq.m.)',
 'Super Built up area 1508.26(140.12 sq.m.)',
 'Super Built up area 2411(223.99 sq.m.)Carpet area: 1808 sq.ft. (167.97 sq.m.)',
 'Super Built up area 1777(165.09 sq.m.)',
 'Carpet area: 4400 (408.77 sq.m.)',
 'Built Up area: 1650 (153.29 sq.m.)Carpet area: 1200 sq.ft. (111.48 sq.m.)',
 'Carpet area: 3344 (310.67 sq.m.)',
 'Super Built up area 1475(137.03 sq.m.)Built Up area: 1350 sq.ft. (125.42 sq.m.)Carpet area: 1250 sq.ft. (116.13 sq.m.)',
 'Carpet area: 1526 (141.77 sq.m.)',
 'Super Built up area 2092(194.35 sq.m.)Built Up area: 1760 sq.ft. (163.51 sq.m.)Carpet area: 1670 sq.ft. (155.15 sq.m.)',
 'Built Up area: 2060 (191.38 sq.m.)Carpet area: 1650 sq.ft. (153.29 sq.m.)',
 'Built Up area: 2191 (203.55 sq.m.)',
 'Super Built up area 3830(355.82 sq.m.)',
 'Built Up area: 2600 (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)',
 'Super Built up area 2979(276.76 sq.m.)',
 'Super Built up area 2200(204.39 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)',
 'Super Built up area 990(91.97 sq.m.)',
 'Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)',
 'Super Built up area 4739(440.27 sq.m.)Built Up area: 3655.35 sq.ft. (339.59 sq.m.)',
 'Super Built up area 2095(194.63 sq.m.)',
 'Super Built up area 2072.9(192.58 sq.m.)',
 'Super Built up area 2086(193.8 sq.m.)',
 'Built Up area: 2251 (209.12 sq.m.)Carpet area: 2250 sq.ft. (209.03 sq.m.)',
 'Super Built up area 4095(380.44 sq.m.)Carpet area: 3500 sq.ft. (325.16 sq.m.)',
 'Carpet area: 2318 (215.35 sq.m.)',
 'Super Built up area 3400(315.87 sq.m.)',
 'Carpet area: 3980 (369.75 sq.m.)',

In [12]:
df['additionalRoom'].unique().tolist()

[nan,
 'Study Room',
 'Servant Room',
 'Pooja Room',
 'Others',
 'Pooja Room,Servant Room',
 'Study Room,Servant Room',
 'Store Room',
 'Study Room,Others',
 'Pooja Room,Study Room,Servant Room',
 'Pooja Room,Study Room',
 'Study Room,Servant Room,Store Room',
 'Study Room,Servant Room,Others',
 'Pooja Room,Store Room',
 'Servant Room,Others,Pooja Room',
 'Servant Room,Others',
 'Servant Room,Store Room',
 'Pooja Room,Study Room,Store Room',
 'Pooja Room,Study Room,Servant Room,Others',
 'Store Room,Servant Room',
 'Pooja Room,Study Room,Servant Room,Store Room',
 'Pooja Room,Study Room,Store Room,Servant Room',
 'Pooja Room,Servant Room,Study Room,Store Room',
 'Servant Room,Pooja Room,Study Room,Store Room',
 'Servant Room,Study Room',
 'Store Room,Pooja Room,Servant Room',
 'Pooja Room,Store Room,Study Room,Servant Room',
 'Pooja Room,Servant Room,Others',
 'Study Room,Pooja Room',
 'Servant Room,Pooja Room',
 'Servant Room,Study Room,Pooja Room,Store Room',
 'Others,Servant Room',
 'Pooja Room,Others',
 'Study Room,Servant Room,Pooja Room,Store Room',
 'Servant Room,Study Room,Store Room',
 'Study Room,Servant Room,Pooja Room',
 'Study Room,Servant Room,Store Room,Pooja Room',
 'Servant Room,Pooja Room,Store Room',
 'Store Room,Study Room',
 'Study Room,Store Room',
 'Servant Room,Pooja Room,Store Room,Study Room',
 'Study Room,Pooja Room,Store Room',
 'Servant Room,Study Room,Pooja Room',
 'Servant Room,Pooja Room,Study Room',
 'Study Room,Pooja Room,Servant Room',
 'Pooja Room,Study Room,Others',
 'Servant Room,Others,Store Room,Pooja Room',
 'Others,Study Room',
 'Servant Room,Study Room,Others',
 'Store Room,Pooja Room']

In [13]:
df['floorNum'].unique().tolist()

['4th\xa0\xa0 of 4 Floors',
 '1st\xa0\xa0 of 3 Floors',
 '12nd\xa0\xa0 of 14 Floors',
 '2nd\xa0\xa0 of 4 Floors',
 '5th\xa0\xa0 of 8 Floors',
 '3rd\xa0\xa0 of 3 Floors',
 '5th\xa0\xa0 of 25 Floors',
 '14th\xa0\xa0 of 27 Floors',
 '2nd\xa0\xa0 of 3 Floors',
 '31st\xa0\xa0 of 40 Floors',
 '1st\xa0\xa0 of 4 Floors',
 '4th\xa0\xa0 of 13 Floors',
 '4th\xa0\xa0 of 15 Floors',
 '3rd\xa0\xa0 of 20 Floors',
 '13rd\xa0\xa0 of 13 Floors',
 '25th\xa0\xa0 of 25 Floors',
 'Ground of 1 Floors',
 'Ground of 14 Floors',
 '11st\xa0\xa0 of 14 Floors',
 '12nd\xa0\xa0 of 13 Floors',
 '11st\xa0\xa0 of 22 Floors',
 '10th\xa0\xa0 of 25 Floors',
 '20th\xa0\xa0 of 20 Floors',
 '5th\xa0\xa0 of 17 Floors',
 '4th\xa0\xa0 of 12 Floors',
 '12nd\xa0\xa0 of 12 Floors',
 '8th\xa0\xa0 of 12 Floors',
 '8th\xa0\xa0 of 8 Floors',
 '21st\xa0\xa0 of 24 Floors',
 'Ground of 11 Floors',
 '6th\xa0\xa0 of 19 Floors',
 '1st\xa0\xa0 of 19 Floors',
 '12nd\xa0\xa0 of 17 Floors',
 '6th\xa0\xa0 of 24 Floors',
 '1st\xa0\xa0 of 25 Floors',
 '9th\xa0\xa0 of 29 Floors',
 '18th\xa0\xa0 of 32 Floors',
 '29th\xa0\xa0 of 31 Floors',
 '3rd\xa0\xa0 of 5 Floors',
 '3rd\xa0\xa0 of 26 Floors',
 '5th\xa0\xa0 of 18 Floors',
 '9th\xa0\xa0 of 12 Floors',
 '6th\xa0\xa0 of 10 Floors',
 '14th\xa0\xa0 of 14 Floors',
 '1st\xa0\xa0 of 11 Floors',
 '8th\xa0\xa0 of 14 Floors',
 '2nd\xa0\xa0 of 2 Floors',
 '4th\xa0\xa0 of 14 Floors',
 '1st\xa0\xa0 of 18 Floors',
 '7th\xa0\xa0 of 19 Floors',
 '3rd\xa0\xa0 of 4 Floors',
 '5th\xa0\xa0 of 20 Floors',
 '9th\xa0\xa0 of 15 Floors',
 '14th\xa0\xa0 of 17 Floors',
 '15th\xa0\xa0 of 20 Floors',
 '6th\xa0\xa0 of 14 Floors',
 '2nd\xa0\xa0 of 12 Floors',
 '3rd\xa0\xa0 of 11 Floors',
 '8th\xa0\xa0 of 13 Floors',
 '11st\xa0\xa0 of 11 Floors',
 '11st\xa0\xa0 of 13 Floors',
 '21st\xa0\xa0 of 41 Floors',
 '2nd\xa0\xa0 of 5 Floors',
 '32nd\xa0\xa0 of 32 Floors',
 '23rd\xa0\xa0 of 26 Floors',
 '6th\xa0\xa0 of 12 Floors',
 '9th\xa0\xa0 of 20 Floors',
 '5th\xa0\xa0 of 15 Floors',
 '43\xa0\xa0 of 47 Floors',
 '1st\xa0\xa0 of 1 Floors',
 '1st\xa0\xa0 of 13 Floors',
 '11st\xa0\xa0 of 12 Floors',
 '14th\xa0\xa0 of 24 Floors',
 '9th\xa0\xa0 of 30 Floors',
 '9th\xa0\xa0 of 9 Floors',
 '32nd\xa0\xa0 of 55 Floors',
 '2nd\xa0\xa0 of 19 Floors',
 '8th\xa0\xa0 of 22 Floors',
 '20th\xa0\xa0 of 32 Floors',
 '2nd\xa0\xa0 of 17 Floors',
 'Basement of 28 Floors',
 '4th\xa0\xa0 of 10 Floors',
 'Ground of 4 Floors',
 '4th\xa0\xa0 of 8 Floors',
 '6th\xa0\xa0 of 20 Floors',
 '16th\xa0\xa0 of 16 Floors',
 '2nd\xa0\xa0 of 14 Floors',
 '12nd\xa0\xa0 of 16 Floors',
 '16th\xa0\xa0 of 18 Floors',
 '6th\xa0\xa0 of 6 Floors',
 '11st\xa0\xa0 of 25 Floors',
 '10th\xa0\xa0 of 18 Floors',
 '2nd\xa0\xa0 of 25 Floors',
 '19th\xa0\xa0 of 41 Floors',
 '18th\xa0\xa0 of 19 Floors',
 '10th\xa0\xa0 of 16 Floors',
 '7th\xa0\xa0 of 20 Floors',
 '10th\xa0\xa0 of 10 Floors',
 '5th\xa0\xa0 of 12 Floors',
 '10th\xa0\xa0 of 20 Floors',
 '20th\xa0\xa0 of 34 Floors',
 '20th\xa0\xa0 of 22 Floors',
 '13rd\xa0\xa0 of 14 Floors',
 '3rd\xa0\xa0 of 19 Floors',
 '7th\xa0\xa0 of 18 Floors',
 '11st\xa0\xa0 of 15 Floors',
 '11st\xa0\xa0 of 21 Floors',
 '16th\xa0\xa0 of 22 Floors',
 '8th\xa0\xa0 of 10 Floors',
 '1st\xa0\xa0 of 35 Floors',
 '18th\xa0\xa0 of 25 Floors',
 '8th\xa0\xa0 of 15 Floors',
 nan,
 '2nd\xa0\xa0 of 16 Floors',
 '17th\xa0\xa0 of 17 Floors',
 '23rd\xa0\xa0 of 28 Floors',
 '30th\xa0\xa0 of 32 Floors',
 'Ground of 3 Floors',
 '11st\xa0\xa0 of 36 Floors',
 '19th\xa0\xa0 of 19 Floors',
 '28th\xa0\xa0 of 28 Floors',
 '7th\xa0\xa0 of 7 Floors',
 'Basement of 4 Floors',
 '15th\xa0\xa0 of 15 Floors',
 '2nd\xa0\xa0 of 34 Floors',
 '9th\xa0\xa0 of 10 Floors',
 '1st\xa0\xa0 of 15 Floors',
 '4th\xa0\xa0 of 34 Floors',
 '4th\xa0\xa0 of 18 Floors',
 '3rd\xa0\xa0 of 15 Floors',
 'Lower Ground of 4 Floors',
 '4th\xa0\xa0 of 40 Floors',
 '6th\xa0\xa0 of 18 Floors',
 '20th\xa0\xa0 of 47 Floors',
 '27th\xa0\xa0 of 48 Floors',
 '6th\xa0\xa0 of 7 Floors',
 '33rd\xa0\xa0 of 48 Floors',
 '35th\xa0\xa0 of 35 Floors',
 '26th\xa0\xa0 of 47 Floors',
 '10th\xa0\xa0 of 17 Floors',
 '10th\xa0\xa0 of 22 Floors',
 'Ground of 24 Floors',
 '3rd\xa0\xa0 of 12 Floors',
 '7th\xa0\xa0 of 25 Floors',
 '3rd\xa0\xa0 of 18 Floors',
 '9th\xa0\xa0 of 14 Floors',
 '14th\xa0\xa0 of 15 Floors',
 '8th\xa0\xa0 of 25 Floors',
 '10th\xa0\xa0 of 14 Floors',
 '3rd\xa0\xa0 of 14 Floors',
 '8th\xa0\xa0 of 34 Floors',
 '8th\xa0\xa0 of 42 Floors',
 '1st\xa0\xa0 of 22 Floors',
 '26th\xa0\xa0 of 34 Floors',
 '21st\xa0\xa0 of 29 Floors',
 '8th\xa0\xa0 of 32 Floors',
 '1st\xa0\xa0 of 12 Floors',
 '39th\xa0\xa0 of 40 Floors',
 '1st\xa0\xa0 of 14 Floors',
 '7th\xa0\xa0 of 9 Floors',
 '22nd\xa0\xa0 of 24 Floors',
 '14th\xa0\xa0 of 20 Floors',
 '8th\xa0\xa0 of 19 Floors',
 '7th\xa0\xa0 of 26 Floors',
 '11st\xa0\xa0 of 30 Floors',
 '1st\xa0\xa0 of 7 Floors',
 '19th\xa0\xa0 of 40 Floors',
 '31st\xa0\xa0 of 32 Floors',
 '14th\xa0\xa0 of 22 Floors',
 '5th\xa0\xa0 of 19 Floors',
 '1st\xa0\xa0 of 10 Floors',
 '15th\xa0\xa0 of 32 Floors',
 '1st\xa0\xa0 of 2 Floors',
 '9th\xa0\xa0 of 26 Floors',
 '33rd\xa0\xa0 of 42 Floors',
 '14th\xa0\xa0 of 18 Floors',
 '5th\xa0\xa0 of 14 Floors',
 '18th\xa0\xa0 of 18 Floors',
 '20th\xa0\xa0 of 23 Floors',
 '9th\xa0\xa0 of 17 Floors',
 '1st\xa0\xa0 of 44 Floors',
 '24th\xa0\xa0 of 31 Floors',
 '2nd\xa0\xa0 of 15 Floors',
 '9th\xa0\xa0 of 16 Floors',
 '26th\xa0\xa0 of 30 Floors',
 '9th\xa0\xa0 of 22 Floors',
 '6th\xa0\xa0 of 17 Floors',
 '14th\xa0\xa0 of 21 Floors',
 '15th\xa0\xa0 of 19 Floors',
 '7th\xa0\xa0 of 14 Floors',
 '16th\xa0\xa0 of 20 Floors',
 '24th\xa0\xa0 of 51 Floors',
 '2nd\xa0\xa0 of 24 Floors',
 '8th\xa0\xa0 of 18 Floors',
 '12nd\xa0\xa0 of 22 Floors',
 '2nd\xa0\xa0 of 36 Floors',
 '19th\xa0\xa0 of 31 Floors',
 '3rd\xa0\xa0 of 9 Floors',
 '4th\xa0\xa0 of 22 Floors',
 '16th\xa0\xa0 of 24 Floors',
 '3rd\xa0\xa0 of 8 Floors',
 '17th\xa0\xa0 of 19 Floors',
 '11st\xa0\xa0 of 26 Floors',
 '19th\xa0\xa0 of 20 Floors',
 'Ground of 16 Floors',
 'Ground of 23 Floors',
 '8th\xa0\xa0 of 26 Floors',
 '4th\xa0\xa0 of 11 Floors',
 '16th\xa0\xa0 of 51 Floors',
 '18th\xa0\xa0 of 21 Floors',
 '2nd\xa0\xa0 of 10 Floors',
 '7th\xa0\xa0 of 10 Floors',
 '14th\xa0\xa0 of 29 Floors',
 '25th\xa0\xa0 of 36 Floors',
 '7th\xa0\xa0 of 23 Floors',
 '21st\xa0\xa0 of 28 Floors',
 '14th\xa0\xa0 of 28 Floors',
 '19th\xa0\xa0 of 24 Floors',
 '5th\xa0\xa0 of 9 Floors',
 '10th\xa0\xa0 of 30 Floors',
 '11st\xa0\xa0 of 20 Floors',
 '11st\xa0\xa0 of 17 Floors',
 '5th\xa0\xa0 of 5 Floors',
 '16th\xa0\xa0 of 27 Floors',
 '6th\xa0\xa0 of 16 Floors',
 '7th\xa0\xa0 of 27 Floors',
 '11st\xa0\xa0 of 18 Floors',
 '17th\xa0\xa0 of 25 Floors',
 '7th\xa0\xa0 of 42 Floors',
 '5th\xa0\xa0 of 30 Floors',
 '16th\xa0\xa0 of 32 Floors',
 '8th\xa0\xa0 of 29 Floors',
 '2nd\xa0\xa0 of 8 Floors',
 '3rd\xa0\xa0 of 32 Floors',
 '6th\xa0\xa0 of 26 Floors',
 '15th\xa0\xa0 of 40 Floors',
 '10th\xa0\xa0 of 15 Floors',
 '9th\xa0\xa0 of 19 Floors',
 '8th\xa0\xa0 of 16 Floors',
 '7th\xa0\xa0 of 12 Floors',
 '2nd\xa0\xa0 of 20 Floors',
 '8th\xa0\xa0 of 11 Floors',
 '7th\xa0\xa0 of 17 Floors',
 '20th\xa0\xa0 of 26 Floors',
 '10th\xa0\xa0 of 12 Floors',
 '7th\xa0\xa0 of 29 Floors',
 '10th\xa0\xa0 of 51 Floors',
 '16th\xa0\xa0 of 21 Floors',
 '8th\xa0\xa0 of 21 Floors',
 '18th\xa0\xa0 of 30 Floors',
 '15th\xa0\xa0 of 30 Floors',
 '25th\xa0\xa0 of 30 Floors',
 '5th\xa0\xa0 of 29 Floors',
 '5th\xa0\xa0 of 26 Floors',
 '12nd\xa0\xa0 of 30 Floors',
 '3rd\xa0\xa0 of 6 Floors',
 '15th\xa0\xa0 of 28 Floors',
 '9th\xa0\xa0 of 28 Floors',
 '10th\xa0\xa0 of 21 Floors',
 '17th\xa0\xa0 of 24 Floors',
 '1st\xa0\xa0 of 26 Floors',
 'Ground of 18 Floors',
 '12nd\xa0\xa0 of 29 Floors',
 '9th\xa0\xa0 of 21 Floors',
 '19th\xa0\xa0 of 29 Floors',
 '9th\xa0\xa0 of 13 Floors',
 '6th\xa0\xa0 of 8 Floors',
 '10th\xa0\xa0 of 19 Floors',
 '9th\xa0\xa0 of 24 Floors',
 '11st\xa0\xa0 of 16 Floors',
 '15th\xa0\xa0 of 39 Floors',
 '10th\xa0\xa0 of 26 Floors',
 '4th\xa0\xa0 of 26 Floors',
 '20th\xa0\xa0 of 40 Floors',
 '13rd\xa0\xa0 of 40 Floors',
 '8th\xa0\xa0 of 40 Floors',
 '16th\xa0\xa0 of 19 Floors',
 '12nd\xa0\xa0 of 18 Floors',
 '6th\xa0\xa0 of 15 Floors',
 '12nd\xa0\xa0 of 15 Floors',
 '5th\xa0\xa0 of 22 Floors',
 '9th\xa0\xa0 of 42 Floors',
 '5th\xa0\xa0 of 16 Floors',
 '8th\xa0\xa0 of 31 Floors',
 '7th\xa0\xa0 of 21 Floors',
 '11st\xa0\xa0 of 29 Floors',
 '6th\xa0\xa0 of 31 Floors',
 '22nd\xa0\xa0 of 30 Floors',
 '15th\xa0\xa0 of 29 Floors',
 '1st\xa0\xa0 of 24 Floors',
 '12nd\xa0\xa0 of 19 Floors',
 '12nd\xa0\xa0 of 25 Floors',
 '4th\xa0\xa0 of 5 Floors',
 '20th\xa0\xa0 of 30 Floors',
 '2nd\xa0\xa0 of 26 Floors',
 '18th\xa0\xa0 of 51 Floors',
 '12nd\xa0\xa0 of 23 Floors',
 '10th\xa0\xa0 of 28 Floors',
 'Ground of 21 Floors',
 '7th\xa0\xa0 of 16 Floors',
 '2nd\xa0\xa0 of 9 Floors',
 '3rd\xa0\xa0 of 16 Floors',
 '12nd\xa0\xa0 of 26 Floors',
 '28th\xa0\xa0 of 30 Floors',
 '10th\xa0\xa0 of 24 Floors',
 '24th\xa0\xa0 of 27 Floors',
 '4th\xa0\xa0 of 20 Floors',
 'Ground of 51 Floors',
 '17th\xa0\xa0 of 30 Floors',
 '19th\xa0\xa0 of 22 Floors',
 '10th\xa0\xa0 of 32 Floors',
 '15th\xa0\xa0 of 25 Floors',
 '19th\xa0\xa0 of 26 Floors',
 '14th\xa0\xa0 of 26 Floors',
 '2nd\xa0\xa0 of 27 Floors',
 '14th\xa0\xa0 of 51 Floors',
 '11st\xa0\xa0 of 24 Floors',
 '17th\xa0\xa0 of 18 Floors',
 '10th\xa0\xa0 of 29 Floors',
 '19th\xa0\xa0 of 39 Floors',
 '6th\xa0\xa0 of 30 Floors',
 '17th\xa0\xa0 of 29 Floors',
 '12nd\xa0\xa0 of 39 Floors',
 '38th\xa0\xa0 of 40 Floors',
 '19th\xa0\xa0 of 30 Floors',
 '7th\xa0\xa0 of 13 Floors',
 'Ground of 12 Floors',
 '10th\xa0\xa0 of 13 Floors',
 '7th\xa0\xa0 of 36 Floors',
 '6th\xa0\xa0 of 29 Floors',
 '18th\xa0\xa0 of 40 Floors',
 '17th\xa0\xa0 of 20 Floors',
 '3rd\xa0\xa0 of 29 Floors',
 'Ground of 13 Floors',
 '5th\xa0\xa0 of 24 Floors',
 '3rd\xa0\xa0 of 27 Floors',
 '12nd\xa0\xa0 of 24 Floors',
 '10th\xa0\xa0 of 11 Floors',
 '2nd\xa0\xa0 of 21 Floors',
 '7th\xa0\xa0 of 15 Floors',
 '11st\xa0\xa0 of 27 Floors',
 '15th\xa0\xa0 of 26 Floors',
 '8th\xa0\xa0 of 24 Floors',
 '27th\xa0\xa0 of 27 Floors',
 '8th\xa0\xa0 of 28 Floors',
 '15th\xa0\xa0 of 17 Floors',
 '2nd\xa0\xa0 of 11 Floors',
 '20th\xa0\xa0 of 25 Floors',
 '5th\xa0\xa0 of 10 Floors',
 '15th\xa0\xa0 of 21 Floors',
 '9th\xa0\xa0 of 18 Floors',
 '4th\xa0\xa0 of 21 Floors',
 '6th\xa0\xa0 of 9 Floors',
 '35th\xa0\xa0 of 51 Floors',
 '22nd\xa0\xa0 of 28 Floors',
 '7th\xa0\xa0 of 22 Floors',
 '14th\xa0\xa0 of 32 Floors',
 '2nd\xa0\xa0 of 40 Floors',
 '10th\xa0\xa0 of 23 Floors',
 '2nd\xa0\xa0 of 13 Floors',
 '2nd\xa0\xa0 of 22 Floors',
 '17th\xa0\xa0 of 21 Floors',
 '3rd\xa0\xa0 of 25 Floors',
 '24th\xa0\xa0 of 24 Floors',
 '8th\xa0\xa0 of 20 Floors',
 '10th\xa0\xa0 of 27 Floors',
 '9th\xa0\xa0 of 27 Floors',
 '21st\xa0\xa0 of 22 Floors',
 '4th\xa0\xa0 of 16 Floors',
 '15th\xa0\xa0 of 16 Floors',
 '15th\xa0\xa0 of 18 Floors',
 '7th\xa0\xa0 of 8 Floors',
 '4th\xa0\xa0 of 39 Floors',
 '24th\xa0\xa0 of 32 Floors',
 '8th\xa0\xa0 of 9 Floors',
 '8th\xa0\xa0 of 27 Floors',
 '21st\xa0\xa0 of 27 Floors',
 '4th\xa0\xa0 of 29 Floors',
 'Ground of 15 Floors',
 '2nd\xa0\xa0 of 32 Floors',
 '17th\xa0\xa0 of 26 Floors',
 '28th\xa0\xa0 of 29 Floors',
 '19th\xa0\xa0 of 21 Floors',
 '18th\xa0\xa0 of 29 Floors',
 '15th\xa0\xa0 of 27 Floors',
 '18th\xa0\xa0 of 24 Floors',
 '3rd\xa0\xa0 of 40 Floors',
 '6th\xa0\xa0 of 21 Floors',
 '3rd\xa0\xa0 of 13 Floors',
 '23rd\xa0\xa0 of 34 Floors',
 '8th\xa0\xa0 of 30 Floors',
 '13rd\xa0\xa0 of 25 Floors',
 '1st\xa0\xa0 of 8 Floors',
 '7th\xa0\xa0 of 24 Floors',
 '1st\xa0\xa0 of 20 Floors',
 '1st\xa0\xa0 of 30 Floors',
 '22nd\xa0\xa0 of 25 Floors',
 '16th\xa0\xa0 of 26 Floors',
 '6th\xa0\xa0 of 25 Floors',
 '4th\xa0\xa0 of 17 Floors',
 '16th\xa0\xa0 of 25 Floors',
 '12nd\xa0\xa0 of 21 Floors',
 '4th\xa0\xa0 of 28 Floors',
 '7th\xa0\xa0 of 32 Floors',
 '30th\xa0\xa0 of 40 Floors',
 '4th\xa0\xa0 of 25 Floors',
 '5th\xa0\xa0 of 23 Floors',
 '19th\xa0\xa0 of 23 Floors',
 '5th\xa0\xa0 of 27 Floors',
 '2nd\xa0\xa0 of 7 Floors',
 '2nd\xa0\xa0 of 18 Floors',
 '6th\xa0\xa0 of 13 Floors',
 '14th\xa0\xa0 of 19 Floors',
 '6th\xa0\xa0 of 11 Floors',
 '8th\xa0\xa0 of 17 Floors',
 'Ground of 17 Floors',
 '3rd\xa0\xa0 of 24 Floors',
 '24th\xa0\xa0 of 39 Floors',
 '20th\xa0\xa0 of 43 Floors',
 '1st\xa0\xa0 of 5 Floors',
 '21st\xa0\xa0 of 51 Floors',
 '12nd\xa0\xa0 of 28 Floors',
 '10th\xa0\xa0 of 34 Floors',
 '16th\xa0\xa0 of 34 Floors',
 '20th\xa0\xa0 of 28 Floors',
 'Ground of 26 Floors',
 '15th\xa0\xa0 of 23 Floors',
 '17th\xa0\xa0 of 23 Floors',
 '18th\xa0\xa0 of 23 Floors',
 '4th\xa0\xa0 of 7 Floors',
 '15th\xa0\xa0 of 24 Floors',
 '12nd\xa0\xa0 of 32 Floors',
 '23rd\xa0\xa0 of 40 Floors',
 '5th\xa0\xa0 of 32 Floors',
 '5th\xa0\xa0 of 13 Floors',
 '1st\xa0\xa0 of 9 Floors',
 '4th\xa0\xa0 of 9 Floors',
 '7th\xa0\xa0 of 11 Floors',
 '20th\xa0\xa0 of 29 Floors',
 '13rd\xa0\xa0 of 18 Floors',
 '12nd\xa0\xa0 of 27 Floors',
 '16th\xa0\xa0 of 30 Floors',
 '7th\xa0\xa0 of 34 Floors',
 '23rd\xa0\xa0 of 29 Floors',
 '13rd\xa0\xa0 of 19 Floors',
 '10th\xa0\xa0 of 39 Floors',
 '21st\xa0\xa0 of 26 Floors',
 '13rd\xa0\xa0 of 21 Floors',
 '25th\xa0\xa0 of 29 Floors',
 '11st\xa0\xa0 of 19 Floors',
 '6th\xa0\xa0 of 22 Floors',
 '6th\xa0\xa0 of 23 Floors',
 '11st\xa0\xa0 of 23 Floors',
 '8th\xa0\xa0 of 23 Floors',
 '19th\xa0\xa0 of 27 Floors',
 '9th\xa0\xa0 of 40 Floors',
 '10th\xa0\xa0 of 40 Floors',
 '13rd\xa0\xa0 of 30 Floors',
 'Ground of 19 Floors',
 '7th\xa0\xa0 of 30 Floors',
 '4th\xa0\xa0 of 27 Floors',
 '13rd\xa0\xa0 of 20 Floors',
 '22nd\xa0\xa0 of 40 Floors',
 '27th\xa0\xa0 of 29 Floors',
 '18th\xa0\xa0 of 26 Floors',
 '15th\xa0\xa0 of 31 Floors',
 '2nd\xa0\xa0 of 28 Floors',
 '15th\xa0\xa0 of 22 Floors',
 '2nd\xa0\xa0 of 6 Floors',
 '4th\xa0\xa0 of 19 Floors',
 '16th\xa0\xa0 of 41 Floors',
 '7th\xa0\xa0 of 40 Floors',
 '12nd\xa0\xa0 of 40 Floors',
 '3rd\xa0\xa0 of 28 Floors',
 '17th\xa0\xa0 of 28 Floors',
 '3rd\xa0\xa0 of 30 Floors',
 '14th\xa0\xa0 of 16 Floors',
 '24th\xa0\xa0 of 30 Floors',
 '3rd\xa0\xa0 of 22 Floors',
 '13rd\xa0\xa0 of 15 Floors',
 '29th\xa0\xa0 of 29 Floors',
 '16th\xa0\xa0 of 31 Floors',
 '5th\xa0\xa0 of 21 Floors',
 '3rd\xa0\xa0 of 17 Floors',
 '12nd\xa0\xa0 of 34 Floors',
 '5th\xa0\xa0 of 34 Floors',
 '9th\xa0\xa0 of 25 Floors',
 '45\xa0\xa0 of 47 Floors',
 '9th\xa0\xa0 of 11 Floors',
 'Ground of 25 Floors',
 '9th\xa0\xa0 of 23 Floors',
 '3rd\xa0\xa0 of 10 Floors',
 '33rd\xa0\xa0 of 33 Floors',
 '1st\xa0\xa0 of 6 Floors',
 '20th\xa0\xa0 of 24 Floors',
 '13rd\xa0\xa0 of 17 Floors',
 'Ground of 6 Floors',
 'Basement of 13 Floors',
 '18th\xa0\xa0 of 22 Floors',
 '17th\xa0\xa0 of 22 Floors',
 '24th\xa0\xa0 of 36 Floors',
 '3rd\xa0\xa0 of 36 Floors',
 '5th\xa0\xa0 of 6 Floors',
 '8th\xa0\xa0 of 35 Floors',
 'Lower Ground of 1 Floors',
 '5th\xa0\xa0 of 35 Floors',
 'Ground of 2 Floors',
 '16th\xa0\xa0 of 36 Floors',
 '10th\xa0\xa0 of 33 Floors',
 '23rd\xa0\xa0 of 23 Floors',
 '18th\xa0\xa0 of 35 Floors',
 '17th\xa0\xa0 of 31 Floors',
 '5th\xa0\xa0 of 11 Floors',
 '1st\xa0\xa0 of 16 Floors',
 '21st\xa0\xa0 of 23 Floors',
 'Ground of 5 Floors',
 'Ground of 40 Floors',
 '1st\xa0\xa0 of 17 Floors',
 '3rd\xa0\xa0 of 33 Floors',
 '13rd\xa0\xa0 of 22 Floors',
 '16th\xa0\xa0 of 35 Floors',
 '44\xa0\xa0 of 47 Floors',
 '23rd\xa0\xa0 of 24 Floors',
 '17th\xa0\xa0 of 47 Floors',
 '4th\xa0\xa0 of 6 Floors',
 '30th\xa0\xa0 of 34 Floors',
 '13rd\xa0\xa0 of 47 Floors',
 '34th\xa0\xa0 of 42 Floors',
 '29th\xa0\xa0 of 39 Floors',
 '18th\xa0\xa0 of 20 Floors',
 '17th\xa0\xa0 of 33 Floors',
 '15th\xa0\xa0 of 45 Floors',
 '3rd\xa0\xa0 of 31 Floors',
 '40th\xa0\xa0 of 40 Floors',
 '27th\xa0\xa0 of 30 Floors',
 '34th\xa0\xa0 of 34 Floors',
 '5th\xa0\xa0 of 36 Floors',
 '19th\xa0\xa0 of 32 Floors',
 '16th\xa0\xa0 of 45 Floors',
 '22nd\xa0\xa0 of 23 Floors',
 '7th\xa0\xa0 of 28 Floors',
 '21st\xa0\xa0 of 36 Floors',
 '14th\xa0\xa0 of 41 Floors',
 'Ground of 29 Floors',
 '22nd\xa0\xa0 of 26 Floors',
 '13rd\xa0\xa0 of 26 Floors',
 '14th\xa0\xa0 of 25 Floors',
 '3rd\xa0\xa0 of 7 Floors',
 'Ground of 22 Floors',
 '13rd\xa0\xa0 of 34 Floors',
 '23rd\xa0\xa0 of 36 Floors']

In [14]:
df['agePossession'].unique().tolist()

['1 to 5 Year Old',
 '10+ Year Old',
 '0 to 1 Year Old',
 'Dec 2023',
 'Under Construction',
 'undefined',
 'Jun 2024',
 'Mar 2024',
 'Dec 2025',
 'By 2023',
 '5 to 10 Year Old',
 'Sep 2025',
 'Jan 2024',
 'Within 6 months',
 'Jan 2027',
 'Dec 2024',
 'Oct 2024',
 'Nov 2023',
 'Jul 2026',
 'Feb 2024',
 'Oct 2023',
 'Jan 2025',
 'Aug 2023',
 nan,
 'By 2024',
 'Apr 2024',
 'Nov 2025',
 'Dec 2026',
 'Within 3 months',
 'Apr 2026',
 'By 2025',
 'Jul 2027',
 'Sep 2023',
 'By 2027',
 'Jan 2026',
 'May 2024',
 'Nov 2024',
 'Aug 2024',
 'Jun 2027',
 'Mar 2025',
 'Jul 2024',
 'Jul 2025',
 'Sep 2027',
 'Jun 2025',
 'Jan 2028',
 'Aug 2026',
 'Mar 2026',
 'Aug 2025',
 'Oct 2025']

In [15]:
df['nearbyLocations'].unique().tolist()

["['Chintapurni Mandir', 'State bank ATM', 'Pearl Dental Clinic', 'Taneja Hospital', 'Dr. Ashok Jain', 'Dr. Madan Clinic', 'Geeta Nursing Home Gurgaon', 'Chiranjiv Hospital', 'Dev Man Kathuria Clinic', 'Aryan Hospital', 'Kr Dental Hub', 'Swastik Maternity and Medical Centre', 'Satyam Hospital Gurgaon', 'Ravi Clinic and Health Care Centre', 'D.R. Rajnis Gupta Clinic', 'Esic Hospital Gurugram', 'Gurgaon Eye Centre', 'Bindal Clinic', 'Shiv Mahima Patient Care Bureau', 'Shree Krishna Hospital Gurgaon', 'M.S Hospital', 'My Care Clinic', 'Ankur Clinic and Maternity Home', 'Triveni Hospital Gurgaon', 'Shri Gobind Hospital', 'Navjeevan Hospital and Maternity Centre', 'Lal Superspeciality Hospital', 'Sparsh Hospital Gurgaon', 'Prateek Nursing Home And Polyclinic', 'Jain Sant Phool Chand Ji Charitable Hospital', 'Sarvodya Hospital', 'Bhatnagar Maternity and Nursing Home', 'Tirath Ram Hospitals Pvt Ltd', 'Dr. Sarvejeet Singh', 'Centre For Sight Gurgaon New Railway Road', 'Dr. Ajay S. Gupta Clinic', 'Kidney Clinic', 'Mangalam Hospital and Heart Centre Gurgaon', 'Sethi Hospital Gurgaon', 'Shubham Hospital Gurgaon', 'Kharbanda Maternity and Nursing Home', 'Gupta Hospital Gurgaon', 'Dentecare - Multispeciality Dental Clinic', 'State bank of india', 'Hdfc bank', 'Kotak bank', 'Indian bank', 'Pizza Hut', 'St. Michaels Sr. Sec. School', 'Dronacharya Government College']",
 '[\'Chintapurni Mandir\', \'Sheetla Mata Mandir\', \'State bank ATM\', \'Sneh Hospital Gurgaon\', \'Jiya Clinic\', \'Dr. Mittal Clinic\', "Dr. Anurag\'s Child Care Clinic", \'Yashroop Medical Centre\', \'Dr. Sindhu Clinic\', \'Bhardwaj Hospital\', \'Jain Sant Phool Chand Ji Charitable Hospital\', \'Sarvodya Hospital\', \'Dr. Hitesh Dawar\', \'Prateek Nursing Home And Polyclinic\', \'R K Hospital Gurgaon\', \'Chirag Hospital Pvt. Ltd\', \'Kr Dental Hub\', \'Gurgaon Eye Centre\', \'Shree Krishna Hospital Gurgaon\', \'Dr. Ashok Jain\', \'GH Gurgaon\', \'Aryan Hospital\', \'Dr. Agya Ram Sharma Clinic\', \'Pearl Dental Clinic\', \'D.R. Rajnis Gupta Clinic\', \'Sparsh Hospital Gurgaon\', \'Bhatnagar Maternity and Nursing Home\', \'Geeta Nursing Home Gurgaon\', \'Taneja Hospital\', \'Ravi Clinic and Health Care Centre\', \'Dr. Sarvejeet Singh\', \'Esic Hospital Gurugram\', \'Centre For Sight Gurgaon New Railway Road\', \'Kidney Clinic\', \'Jackson Hospital\', \'Jeevan Jyoti Hospital Gurgaon\', \'Chiranjiv Hospital\', \'Dr. Tomar Clinic\', \'Indian bank\', \'Kotak bank\', \'Hdfc bank\', \'State bank of india\', \'Pizza Hut\', \'St. Michaels Sr. Sec. School\', \'Lieutenant Atul Kataria School\', \'Dronacharya Government College\', \'Gurgaon railway station\', \'Gurgaon railway station\', \'Gurgaon railway station\']',
 "['Huda City Metro', 'Golf Course extn road', 'Rajiv Chowk', 'IGI Airport', 'IMT Sohna', 'Damdama Lake']",
 "['Sector 55-56 Metro station', 'Bestech Central Square Mall', 'Golf Course Ext Road', 'Badshahpur Sohna Rd Hwy', 'ORCHIDS The International School', 'Sushant University', 'Marengo Asia Hospitals', 'Indira Gandhi Intl Airport', 'Gurgaon Railway Station']",
 "['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. Sarkar Clinic', 'Sagar Clinic', 'Orris Community Center', 'Vijay Petrol Pump', 'HP Petrol Pump', 'Essar Petrol Pump', 'Indian Oil', 'Pizza Hut', 'KFC']",
 nan,
 "['Shri Multispeciality Hospital', 'Esic Hospital Gurugram', 'Shree Krishna Hospital Gurgaon', 'Dr. Hitesh Dawar', 'Prateek Nursing Home And Polyclinic', 'Kr Dental Hub', 'Basai dhankot railway station']",
 '[\'IFFCO Chowk Metro Station\', \'The Esplanade Mall\', \'Dhanwapur Road\', \'Dwarka Expressway\', \'Govt. PG College\', \'Delhi Public School\', \'The NorthCap University\', \'Shree Krishna Hospital\', \'Indira Gandhi International Airport\', \'Basai Dhankot\', \'The Executive Centre\', \'Park Inn\', "Oyster\'s Water Park", \'DLF Golf and Country Club\']',
 "['Dwarka Expressway', 'Adarsh public school,Garhi Harsaru', 'Excellere World School', 'PHC Garhi Harsaru', 'Aman Hospital & Surgical Centre', 'Garhi Harsaru Junction', 'Neemrana Palace']",
 "['Sapphire 83 Mall', 'NH-8', 'Bal Bharti Public School', 'KIIT College of Engineering', 'Miracles Apollo Cradle', 'Indira Gandhi International Airport', 'IMT Manesar', 'Savoy Suites, Manesar', 'De Adventure Park', 'Manesar Golf Course']",
 '[\'Ambience Mall New\', \'Dwarka Expressway\', \'NH8\', "St. Xavier\'s High School", \'Miracles Apollo Cradle\', \'Hyatt Regency Gurgaon\', \'Nakhrola Stadium\']',
 "['The roadside cafe', 'GD Goenka Mess', 'ROyal Kitchen', 'Mithaas Wala', 'Momomia Gurgoan']",
 '[\'Petrol Pump Indian Oil\', \'Petrol Pump\', \'Rao Dhaba\', "McDonald\'s"]',
 "['IRIS Broadway Mall', 'Dwarka Expressway', 'Saraswati Model School', 'SGT University', 'Aarvy Healthcare Hospital', 'Indira Gandhi International Airport', 'Garhi Harsaru Junction', 'Orchid Business Park', 'Holiday Inn Gurugram Sector 90', 'Flying Wings Badminton Academy']",
 "['Dwarka Sector 21', 'Dwarka Expressway', 'Vasant Kunj', 'The Shikshiyan School', 'The NorthCap University', 'Rions Hospital', 'IGI Airport', 'Gurgaon', 'WTC Plaza', 'Luxus Haritma Resort', 'Fun N Food WaterPark', 'BSF Golf Course', 'Nehru Stadium']",
 "['Radhakrishna Shani Mandir', 'Sanatan Dharm Mandir', 'Standard chartered ATM', 'Icici bank ATM', 'State bank ATM', 'Vatsalya Clinic', 'Anand Hospital Gurgaon', 'pracksht hospital', 'Kriti Hospital', 'Bones Clinic - Orthopaedics', 'Meher Clinic', 'Surgicare Hospital Gurgaon', 'Skin Clinic', 'Divine Look Clinic Centre', 'Dr. Naresh Pandita', 'Dr. Anuj Sharma', 'Vishesh Dental', 'Neelkanth Health Care', 'Park Hospital Gurgaon', 'Dr. Aruna Kalra', 'Wellness Eye Centre', 'Best Urologist Atcomplete Family Clinic', 'Wembley estate club', 'HUDA Office Complex', 'Medisca', 'Genius', 'Gardian Pharmacy', 'Apollo Pharmacy', 'SPAZE BUSINESS PARK', 'Unitech', 'Hdfc bank', 'Hdfc bank and atm', 'Hdfc bank', 'Hdfc bank', 'Indusind bank', '222', 'Madison and Pike', 'Pizza Hut', 'India', 'Haldiram', 'Kamla International', 'Gurugram University', 'Amity Global School']",
 "['Khan Market', 'The Esplanade Mall', 'Dwarka Expressway', 'Garhi Road', 'Delhi Public School', 'SGT University', 'Aryan Hospital', 'Indira Gandhi Int. Airport', 'Basai Dhankot', 'The Executive Centre', 'Inde Hotels & Resorts', 'Appu Ghar', 'DLF Golf and Country Club']",
 "['Huda Metro Station', 'V3S Sapphire Ninety', 'IMT Road', 'Pataudi Road', 'Dwarka Expy', 'RPS International School', 'Euro International School', 'SGT University', 'Arc Multi Speciality hospital', 'Indira Gandhi Intl Airport', 'Farrukh Nagar Railway Station']",
 "['Airia Mall', 'NH 248A', 'NE 4, Haryana', 'GD Goenka Signature School', 'K. R. Mangalam University', 'Lady Florence Convent School Sohna', 'Vardaan Hospital & Trauma Centre', 'Indira Gandhi International Airport', 'Gurgaon Railway Station', 'Country Inn & Suites By Radisson', 'Tau Devilal Stadium Sohna']",
 "['Sant Soordas Sihi Metro Station', 'Airia Mall', 'Dwarka Expressway', 'Pataudi Road', 'NH-8', 'KMP Expressway', 'RPS International School', 'Genesis Hospital Sector 84', 'Gurgaon Railway Station', 'Vatika Business Park Sector 49', 'Holiday Inn Gurugram Sector 90', 'De Adventure Amusement Park', 'National Tennis Academy Sector 98', 'IMT Manesar']",
 "['Sapphire 83 Mall', 'NH -8', 'Golf Course Extension Road', 'Mount Olympus Junior School', 'Amity University Gurugram', 'Miracles Apollo Hospital', 'Indira Gandhi International Airport', 'IMT Manesar', 'Savoy Suites, Manesar', 'Golden Greens Golf & Resorts']",
 "['Satya The Hive Mall', 'Gurugram Road', 'Dwarka Expy', 'Gurugram Global Heights School', 'Sunrise University', 'The Signature Super Speciality Hospital', 'Indira Gandhi Intl Airport', 'Basai Dhankot Railway Station', 'Country Inn & Suites by Radisson', 'Nehru Stadium']",
 '[\'Dwarka Sector 21\', \'Pacific D21 Mall\', \'Bajghera Road\', \'Dwarka Expy\', \'Euro International School, Sector- 109.\', \'The NorthCap University\', "Rion\'s Hospital", \'Indira Gandhi Intl Airport\', \'Bijwasan Railway Station\']',
 '[\'Pooja Clinic\', \'Dr. Sahil Clinic\', \'Prakash Hospital\', \'Shri Rade Clinic\', \'Yadav Dental & Eye Care\', \'Dental Hospital\', \'Petrol pump Maitri motors\', \'Petrol Pump\', "McDonald\'s", "McDonald\'s", \'Rao Dhaba\']',
 "['Sector 54 Chowk Metro Station', 'Sahara Mall', 'NH 248A', 'Shiksha Bharti Public School', 'Gurugram University', 'Park Hospital', 'Indira Gandhi International Airport', 'Garhi Harsaru Junction', 'Holiday Inn Express Gurugram']",
 "['Decathlon Sohna Road', 'Raheja Mall', 'Elements One Mall', 'GD Goenka Public School', 'Mount Olympus School', 'Basant Valley Global School', 'Lotus Valley School', 'Park Hospital (Gurugram, Haryana)', 'CK Birla Hospital', 'CDAS Super Speciality Hospital', 'Orchid Business Park', 'Candor TechSpace', 'JMD Megapolis', 'Splendor Trade Tower', 'DoubleTree by Hilton']",
 "['Kamla Hospital Gurgaon', 'Shri Multispeciality Hospital', 'Shri Balaji Hospital and Trauma Center', 'Yadav Hospital Gurgoan', 'Chandna Dental Surgery Orthodontic and Implant Centre', 'The Muskan Dental Clinic', 'Harshila Dental Clinic', 'Dental Xpert Dental Clinic', 'Gautam Hospital', 'Clove Dental', 'Esic Hospital Gurugram', 'Sai Dental Clinic', 'Sunrise Hospital Gurgaon', 'Bhanu Dental Care', 'Nutan Dental Hospital', 'Ankur Clinic and Maternity Home', 'Shri Ram Dental Clinic', 'Mangalam Hospital and Heart Centre Gurgaon', 'Navjeevan Hospital and Maternity Centre', 'Parmar Dental Clinic & Lab', 'Ayushman Hospital And Trauma Centre', 'Shiv Mahima Patient Care Bureau', 'Rachna Dental Clinic', 'Vaishnavi Nursing Home', 'Shri Gobind Hospital', 'Lal Superspeciality Hospital', 'Shree Krishna Hospital Gurgaon', 'Dr. Madan Clinic', 'Taneja Hospital', 'Dev Man Kathuria Clinic', 'Boxer Fuel Point', 'Basai dhankot railway station']",
 '[\'Chintapurni Mandir\', \'Sheetla Mata Mandir\', \'State bank ATM\', \'Sneh Hospital Gurgaon\', \'Jiya Clinic\', \'Dr. Mittal Clinic\', "Dr. Anurag\'s Child Care Clinic", \'Yashroop Medical Centre\', \'Dr. Sindhu Clinic\', \'Jain Sant Phool Chand Ji Charitable Hospital\', \'Sarvodya Hospital\', \'Bhardwaj Hospital\', \'Dr. Hitesh Dawar\', \'R K Hospital Gurgaon\', \'Prateek Nursing Home And Polyclinic\', \'Chirag Hospital Pvt. Ltd\', \'Kr Dental Hub\', \'Gurgaon Eye Centre\', \'Shree Krishna Hospital Gurgaon\', \'Dr. Ashok Jain\', \'GH Gurgaon\', \'Aryan Hospital\', \'Dr. Agya Ram Sharma Clinic\', \'Sparsh Hospital Gurgaon\', \'D.R. Rajnis Gupta Clinic\', \'Pearl Dental Clinic\', \'Bhatnagar Maternity and Nursing Home\', \'Geeta Nursing Home Gurgaon\', \'Ravi Clinic and Health Care Centre\', \'Taneja Hospital\', \'Dr. Sarvejeet Singh\', \'Centre For Sight Gurgaon New Railway Road\', \'Kidney Clinic\', \'Jeevan Jyoti Hospital Gurgaon\', \'Jackson Hospital\', \'Esic Hospital Gurugram\', \'Dr. Tomar Clinic\', \'Children Hospital\', \'Indian bank\', \'Kotak bank\', \'Hdfc bank\', \'State bank of india\', \'Pizza Hut\', \'St. Michaels Sr. Sec. School\', \'Lieutenant Atul Kataria School\', \'Dronacharya Government College\', \'Gurgaon railway station\', \'Gurgaon railway station\', \'Gurgaon railway station\']',
 '[\'Palam Vihar Vyapar kendra\', \'Palam triangle\', \'Ram Mandir\', \'Kalyan Hospital Gurgaon\', \'Metro Hospital and Heart Institute Gurgaon\', \'DGD Bamnoli\', "DR KAPOOR\'S Dental Care and Implant Centre", \'Axis bank\', \'Big Cinemas\', \'Cafe Coffee Day\', \'Pizza Hut\', "Domino\'s Pizza", \'Moti Mahal\', \'Pind Baluchi\', "McDonald\'s", \'Chiranjiv Bharati School\', \'Masti ki Pathshala Teach India\', \'Palam vihar railway station\']',
 '[\'Sector 42-43 metro station\', \'Sector 53-54 metro station\', \'Hanuman Mandir\', \'New Life Church\', \'Hdfc ATM\', \'Rbs ATM\', \'Hdfc bank ATM\', \'Standard chartered ATM\', \'Kotak mahindra bank ATM\', \'Standard chartered ATM\', \'Paras Hospital Gurgaon\', \'Arihant Hospital\', \'Gupta\', \'Marwah Clinic\', \'The Dental Lounge\', \'Sitaram Bhartia\', \'Dr. Naval Mendiratta\', \'Fortis Memorial Research Institute Fortis Vivekanand Hospital\', \'Max Hospital\', \'Guardian Pharmacy\', \'Chikitsa\', \'Bharat petroleum\', \'Hdfc bank & atm\', \'Icici bank\', \'Hdfc bank\', \'Axis bank\', \'Sagar Ratna\', \'Cafe Tonini\', \'Shophouse by Kylin\', "Carl\'s Jr.", \'Starbucks\', \'Clock tower\', \'Balaji Vegetarian Paradise\', \'The Chicken Boat\', \'PWO house\', \'Naveidyam\', \'Blue Tokai Coffee Roasters\', \'Starbucks\', \'Nowhere Brewpub and cafe\', \'Fat\', \'Dighent cafe\', \'Drunken Monkey\', \'Stones2milestones\', \'Ncr library\', \'Bahrisons library\']',
 "['Reliance Trends Newtown Square Mall', 'Pataudi Rd, Harsaru', 'Euro Intl School, Sector 37D, Gurugram', 'SGT University', 'Genesis Hospital', 'Indira Gandhi Intl Airport']",
 '[\'Huda city centre metro station\', \'Iffco chowk metro station\', \'Axis bank ATM\', \'Punjab national bank ATM\', \'Hdfc ATM\', \'Axis bank ATM\', \'Citi bank ATM\', \'Icici ATM\', \'Citi bank ATM\', \'Icici bank ATM\', \'Centre For Sight Gurgaon Sector 29\', \'Sangwan Hospital Gurgaon\', \'Shivam Hospital Gurgaon\', \'Umkal Hospital\', \'Dr. Kutbuddin Akbary\', \'Max Hospital\', \'Dr. Naval Mendiratta\', \'Fortis Memorial Research Institute Fortis Vivekanand Hospital\', \'Community Center Sukhrali\', \'Gardian Pharmacy\', \'City Medical\', \'Pizza Hut\', "Hops \'N\' Brew", \'Spaghetti Kitchen & Bar\', "Domino\'s Pizza", "McDonald\'s", \'Tocpao\', \'Zura\', \'Beer & Whisky Bar\', \'The Oriental Bloom Chinese and Thai\', \'Gola Sizzles\', \'Ardor 29\', \'ADDA\', \'Gung the palace Korean restaurant\', \'Walking Street\', \'MoB Ministory of Beer\', \'Park Baluchi\', \'Bikanervala\', \'Dhabba\', \'Black Mambaa\', \'Gravity Space Bar\', \'KFC\', \'Swagath\', \'distillery\', \'Roots\', \'Cafe Coffee Day\', \'32nd Milestone\', \'Pizza Hut\', \'Management Development Institute\', \'Salvan Public School\']',
 '[\'Sri Radhe Krishna Temple\', \'Icici bank ATM\', \'Kamal Hospital and Maternity Centre\', \'Gobind Hospital\', \'Sona Devi Memorial Hospital and Trauma Centre\', \'Sanjeevani Hospital Gurgaon\', \'Sai Dharamraj Hospital\', \'Sai Heart and Trauma Center\', \'Ekta Hospital\', \'Divine Look Clinic Centre\', \'Skin Clinic\', \'Kore Tech Park\', \'SPAZE BUSINESS PARK\', \'Icici bank\', \'State bank of india\', \'Union bank of india\', \'Central bank of india\', \'Indusind bank\', \'Hdfc bank\', \'SRS Cinemas\', \'Starbucks\', \'Nook\', "Nirula\'s", "Domino\'s Pizza", \'India\']',
 "['Gyaananda School', 'The NorthCap University', 'Park Hospital', 'IGI Airport', 'Gurgaon Station', 'WTC Plaza', 'Altrade Business Centre', 'Radisson Blu Hotel']",
 '[\'Huda City Centre\', \'Omaxe City Centre\', \'Ninex City Mart\', \'Vaels Ravindra Bharathi Global School\', \'Anjali nursery\', \'Polaris Hospital\', \'Axis Bank\', \'Triangular Park\', \'Flow Sports Life Badminton Club\', \'Basai Dhankot Railway Station\', \'Cars24\', \'Radisson Hotel Gurugram\', "McDonald\'s", \'Petrol Pump\', \'Indian Post Office\']',
 "['The Esplanade Mall', 'Gurgaon Road', 'Delhi Jaipur Expressway', 'Green Field Public School', 'Sunrise University', 'K.D. Hospital', 'Indira Gandhi International Airport', 'Gurgaon Railway Station', 'infinity Business Park']",
 '[\'Huda city centre metro station\', \'Sector 42-43 metro station\', \'Hanuman Mandir\', \'New Life Church\', \'Hdfc ATM\', \'Standard chartered ATM\', \'Hdfc bank ATM\', \'Rbs ATM\', \'Icici ATM\', \'Citi bank ATM\', \'Axis bank ATM\', \'Hdfc ATM\', \'Kotak mahindra bank ATM\', \'Standard chartered ATM\', \'Gupta\', \'Arihant Hospital\', \'Paras Hospital Gurgaon\', \'Fortis Memorial Research Institute Fortis Vivekanand Hospital\', \'Dr. Naval Mendiratta\', \'Dr. Kutbuddin Akbary\', \'Max Hospital\', \'Pernod Ricard Charitable Dispensary\', \'Guardian Pharmacy\', \'Chikitsa\', \'Gardian Pharmacy\', \'City Medical\', \'Bharat petroleum\', \'Icici bank\', \'Hdfc bank\', \'Axis bank\', \'PWO house\', \'Balaji Vegetarian Paradise\', \'The Chicken Boat\', \'Naveidyam\', \'Sagar Ratna\', \'Cafe Tonini\', \'Shophouse by Kylin\', "Carl\'s Jr.", \'Starbucks\', \'CCD\', \'Stones2milestones\', \'School of Inspired Leadership SOIL\', \'St. Angels Sr\', \'St. Angels Jr\', \'Ncr library\', \'Bahrisons library\']',
 "['Discount Department Store', 'Badshahpur Sohna Rd Hwy, Sohna Rural', 'GD Goenka University, Gurugram', 'Sohna Public School Pathane Ware', 'Vardaan Hospital & Trauma Centre', 'Indira Gandhi Intl Airport']",
 "['Huda metro station', 'Gurgaon Dreamz Mall', 'Dwarka Expressway', 'Delhi Ajmer Expressway', 'Euro International School, Sector- 109', 'The NorthCap University', 'Metro Hospital, Palam Vihar', 'Gurgaon Railway Station', 'Infinity Business Park']",
 "['Vatika City Centre Mall', 'Pataudi Road', 'Broadways International School', 'DPG Institute of Technology', 'Aarvy Healthcare', 'Indira Gandhi International Airport', 'Sultanpur National Park', 'Imt Manesar', 'Holiday Inn Gurugram', 'SkyJumper Trampoline Park', 'HUDA Mini Golf Course']",
 '[\'Palam Vihar Vyapar kendra\', \'Palam triangle\', \'Chintapurni Mandir\', \'Sheetla Mata Mandir\', \'Ram Mandir\', \'State bank ATM\', \'Jiya Clinic\', \'Dr. Mittal Clinic\', "Dr. Anurag\'s Child Care Clinic", \'Yashroop Medical Centre\', \'Chirag Hospital Pvt. Ltd\', \'Kalyan Hospital Gurgaon\', \'R K Hospital Gurgaon\', \'Sneh Hospital Gurgaon\', \'Dr. Sindhu Clinic\', \'Bhardwaj Hospital\', \'Sarvodya Hospital\', \'Jain Sant Phool Chand Ji Charitable Hospital\', \'GH Gurgaon\', \'Jeevan Jyoti Hospital Gurgaon\', \'Dr. Hitesh Dawar\', \'Gurgaon Eye Centre\', \'Children Hospital\', \'Dr. Tomar Clinic\', \'Dr. Agya Ram Sharma Clinic\', \'Sheetla Clinic\', \'Prateek Nursing Home And Polyclinic\', \'Nidhi Clinic\', \'Dr. Babita Sharma\', \'Kishor Clinic\', \'Sparsh Hospital Gurgaon\', \'Kr Dental Hub\', \'Bhatnagar Maternity and Nursing Home\', \'Axis bank\', \'Indian bank\', \'Kotak bank\', \'Hdfc bank\', \'Big Cinemas\', "McDonald\'s", \'Pizza Hut\', \'Moti Mahal\', \'Pind Baluchi\', \'Cafe Coffee Day\', \'Lieutenant Atul Kataria School\', \'Gurgaon railway station\', \'Gurgaon railway station\', \'Gurgaon railway station\']',
 "['Sector 55-56 metro', 'Global city centre', 'Sohna road dhunela', 'Gd goenka university', 'Maharana pratap school', 'Vardaan hospital and trauma centre', 'Indira Gandhi International Airport', 'Garhi harsaru railway station Gurgaon']",
 "['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RHM Public School', 'Silver Streak Multi Speciality Hospital', 'Airport', 'Holiday Inn Gurugram']",
 "['MG Road Metro Station', 'NeoSquare Shopping Mall', 'Dwarka Expressway', 'Glorious World School', 'DPG Institute of Technology', 'Chirag Hospital', 'Indira Gandhi International Airport', 'Gurgaon', 'Country Inn & Suites by Radisson', 'SkyJumper Trampoline Park', 'Hamoni Golf Camp']",
 "['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka Expy', 'Euro International School', 'Sushant University', 'Shri Balaji’s Multispeciality Hospital', 'Indira Gandhi Intl Airport', 'Garhi Harsaru Junction']",
 "['Sapphire 83', 'NH 48', 'Cambridge Montessori', 'Miracles Apollo Hospital', 'IGI Airport', 'Garhi Harsaru Junction', 'Hyatt Regency']",
 "['WorldMark Gurgaon', 'Sohna Road', 'Golf Course Road', 'CK Birla Hospital', 'Delhi International Airport', 'Lemon Tree Hotel']",

In [16]:
df = (
    pd
    .read_csv("01_flats.csv")    #reading data from csv file
    
    .drop_duplicates()    #removing duplicate rows if present
    
    .dropna(subset=['price','society','areaWithType','bathroom','balcony',
                    'floorNum','agePossession','nearbyLocations','description'])    #removing rows where mandatory data is NA
    
    .apply(lambda col: col.str.strip().str.lower() if col.dtype=='object' else col)    #all data to lower case
    
    .assign(
        bhk = lambda df_: df_['property_name'].str.extract(r"(\d{1})").astype('int8')    #extracting the value of BHK
        
        ,locality = lambda df_: df_['property_name'].str.split('in ').str[1]    #extracting the name of locality
        
        ,society = lambda df_: df_['society'].str.split(r"(\d{1}\.{1}\d*)").str[0]    #extracting the name of society
        
        ,price_cr = lambda df_: df_['price'].str.replace('₹','').apply(
                                lambda x: x.replace('crore','').strip() if 'crore' in x 
                                    else round(float(x.replace('lac','').strip())/100,2) if 'lac' in x 
                                        else np.nan).astype('float')    #price in crore Rupees
        
        ,bathroom = lambda df_: df_['bathroom'].str.extract(r"(\d+)").astype('int8')    #number of bathrooms
        
        ,balcony = lambda df_: df_['balcony'].str.extract(r"(\d*)").replace('','0').astype('int8')    #number of balconies
        
        ,area_sqft = lambda df_: df_['areaWithType'].str.extract(r"(\d*.?\d+)").astype('float')    #intermediate step
        ,area_sqmm = lambda df_: df_['areaWithType'].str.extract(r"(\(\d+\.?\d+\s*.*m{1}|M{1})")    #intermediate step
        
        ,area_sqm = lambda df_: df_['area_sqmm'].str.extract(r"(\d+.?\d+)")
                                .astype('float').fillna(df_['area_sqft']/10.764)    #extracting the area in sq.m.
        
        ,area_type = lambda df_: df_['areaWithType'].str.split(' area').str[0].str.strip()    #type of area
        
        ,addl_room = lambda df_: np.where(df_['additionalRoom'].notna(), 1, 0).astype('int8')    #if additional room is present
        
        ,floor_no = lambda df_: df_['floorNum'].str.extract(r"(\d+)").fillna('0').astype(int)    #floor no. of the flat
        
        ,floor_rise = lambda df_: np.where(df_['floor_no']<4, 'low', 
                                      np.where(df_['floor_no']<8, 'mid', 'high'))    #floor-rise of the flat
        
        ,age_1 = lambda df_: df_['agePossession'].str.replace('within 3 months','0').str.
                                replace('within 6 months','0').str.findall(r"(\d+)").str[0].fillna(-1).astype(int).
                                    apply(lambda x: 2026-x if x>1000 else x)    #age in years
        
        ,age = lambda df_: np.where(df_['age_1']<0, 'under construction',
                                    np.where(df_['age_1']<2, 'new', 
                                        np.where(df_['age_1']<5, 'mid aged', 'old')))    #relative age
        
        ,nearby_loc = lambda df_: df_['nearbyLocations'].apply(lambda x: re.findall(r"'(.*?)'",str(x)))    #list of nearby loc.
    )
    
    .drop(columns=['property_name','link','property_id','bedRoom','price',
                   'areaWithType','area_sqft','area_sqmm','additionalRoom',
                   'floorNum','floor_no','agePossession','age_1','nearbyLocations',
                   'address','description','facing','features'])    #removing unnecessary columns
    
    .reindex(columns=['price_cr','bhk','bathroom','balcony','addl_room','floor_rise','area_sqm',
                      'area_type','age','society','locality','furnishDetails','nearby_loc'])    #rearranging columns
    
    .reset_index(drop=True)    #resetting index
)

df.sample(3)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
1864,1.55,2,2,3,0,low,123.56,super built up,new,la vida by tata housing,sector 113 gurgaon,"['2 light', 'no ac', 'no bed', 'no chimney', '...","[dwarka sector 21, pacific d21 mall, bajghera ..."
127,0.26,2,2,1,0,low,44.76,carpet,new,mvn athens,sohna,"['1 wardrobe', '3 fan', '1 geyser', '3 light',...","[sbi atm, axis bank atm, uco bank atm, corpora..."
2155,1.50,3,3,3,0,mid,162.58,super built up,under construction,ats marigold,sector 89 a gurgaon,"['1 fan', '1 light', '1 ac', '1 modular kitche...","[reliance trends newtown square mall, dwarka e..."

In [17]:
df.to_csv('03_flats_cleaned.csv', index=False)