In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv("05_flats_FeatureEngineered.csv")

In [4]:
df.shape

(2911, 50)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price_cr                2904 non-null   float64
 1   area_sqm                2911 non-null   float64
 2   bhk                     2911 non-null   int64
 3   bathroom                2911 non-null   int64
 4   balcony                 2911 non-null   int64
 5   addl_room               2911 non-null   int64
 6   sector                  2911 non-null   int64
 7   landmark_count          2911 non-null   int64
 8   has_hospital_or_clinic  2911 non-null   int64
 9   has_police_stn          2911 non-null   int64
 10  has_fire_stn            2911 non-null   int64
 11  has_mall                2911 non-null   int64
 12  has_market              2911 non-null   int64
 13  has_park                2911 non-null   int64
 14  has_bank_or_atm         2911 non-null   int64
 15  has_institute           2911 non-null   int64
 16  has_airport             2911 non-null   int64
 17  has_rly_stn             2911 non-null   int64
 18  has_metro_stn           2911 non-null   int64
 19  has_expy                2911 non-null   int64
 20  has_petrol_pump         2911 non-null   int64
 21  has_hotel               2911 non-null   int64
 22  has_temple_or_church    2911 non-null   int64
 23  has_famous_chowk        2911 non-null   int64
 24  has_club                2911 non-null   int64
 25  has_stadium             2911 non-null   int64
 26  has_restro_cafe         2911 non-null   int64
 27  fan                     2911 non-null   int64
 28  light                   2911 non-null   int64
 29  wardrobe                2911 non-null   int64
 30  ac                      2911 non-null   int64
 31  bed                     2911 non-null   int64
 32  chimney                 2911 non-null   int64
 33  curtains                2911 non-null   int64
 34  dining table            2911 non-null   int64
 35  exhaust fan             2911 non-null   int64
 36  geyser                  2911 non-null   int64
 37  modular kitchen         2911 non-null   int64
 38  microwave               2911 non-null   int64
 39  fridge                  2911 non-null   int64
 40  sofa                    2911 non-null   int64
 41  stove                   2911 non-null   int64
 42  tv                      2911 non-null   int64
 43  washing machine         2911 non-null   int64
 44  water purifier          2911 non-null   int64
 45  area_type               2911 non-null   object
 46  floor_rise              2911 non-null   object
 47  age                     2911 non-null   object
 48  society                 2911 non-null   object
 49  city                    2911 non-null   object
dtypes: float64(2), int64(43), object(5)
memory usage: 1.1+ MB

In [3]:
df.head(2)

,price_cr,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,...,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city
0,0.45,83.61,2,2,1,0,7,50,34,0,...,0,1,0,1,0,carpet,mid,new,maa bhagwati residency,gurgaon
1,0.50,60.39,2,2,1,0,3,48,4,0,...,0,1,0,1,0,carpet,low,old,apna enclave,gurgaon

In [12]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
price_cr,2904.0,NaN,NaN,NaN,1.729607,1.406123,0.16,0.9,1.4,2.09,15.0
area_sqm,2911.0,NaN,NaN,NaN,255.48643,2117.57303,6.69,120.77,161.19,199.74,68483.2
bhk,2911.0,NaN,NaN,NaN,2.810374,0.791129,1.0,2.0,3.0,3.0,6.0
bathroom,2911.0,NaN,NaN,NaN,2.967365,1.045018,1.0,2.0,3.0,4.0,7.0
balcony,2911.0,NaN,NaN,NaN,2.460666,0.789372,0.0,2.0,3.0,3.0,3.0
addl_room,2911.0,NaN,NaN,NaN,0.576434,0.494208,0.0,0.0,1.0,1.0,1.0
sector,2911.0,NaN,NaN,NaN,70.537616,28.826174,1.0,51.0,78.0,91.0,142.0
landmark_count,2911.0,NaN,NaN,NaN,14.299897,11.384368,3.0,9.0,10.0,14.0,50.0
has_hospital_or_clinic,2911.0,NaN,NaN,NaN,2.272415,4.712307,0.0,1.0,1.0,1.0,42.0
has_police_stn,2911.0,NaN,NaN,NaN,0.014772,0.120658,0.0,0.0,0.0,0.0,1.0
has_fire_stn,2911.0,NaN,NaN,NaN,0.000687,0.026207,0.0,0.0,0.0,0.0,1.0
has_mall,2911.0,NaN,NaN,NaN,0.5517,0.553641,0.0,0.0,1.0,1.0,3.0
has_market,2911.0,NaN,NaN,NaN,0.195465,0.493873,0.0,0.0,0.0,0.0,4.0
has_park,2911.0,NaN,NaN,NaN,0.620749,0.773111,0.0,0.0,0.0,1.0,4.0
has_bank_or_atm,2911.0,NaN,NaN,NaN,1.10134,2.956681,0.0,0.0,0.0,0.0,14.0
has_institute,2911.0,NaN,NaN,NaN,1.62865,1.234884,0.0,1.0,2.0,2.0,8.0
has_airport,2911.0,NaN,NaN,NaN,0.576091,0.494261,0.0,0.0,1.0,1.0,1.0
has_rly_stn,2911.0,NaN,NaN,NaN,0.199588,0.536963,0.0,0.0,0.0,0.0,4.0
has_metro_stn,2911.0,NaN,NaN,NaN,0.443147,0.846732,0.0,0.0,0.0,1.0,8.0
has_expy,2911.0,NaN,NaN,NaN,0.443834,0.609931,0.0,0.0,0.0,1.0,2.0
has_petrol_pump,2911.0,NaN,NaN,NaN,0.295775,0.903285,0.0,0.0,0.0,0.0,8.0
has_hotel,2911.0,NaN,NaN,NaN,0.323257,0.480126,0.0,0.0,0.0,1.0,2.0
has_temple_or_church,2911.0,NaN,NaN,NaN,0.191343,0.528377,0.0,0.0,0.0,0.0,3.0
has_famous_chowk,2911.0,NaN,NaN,NaN,0.118859,0.376671,0.0,0.0,0.0,0.0,3.0
has_club,2911.0,NaN,NaN,NaN,0.08966,0.31218,0.0,0.0,0.0,0.0,3.0
has_stadium,2911.0,NaN,NaN,NaN,0.07695,0.266557,0.0,0.0,0.0,0.0,1.0
has_restro_cafe,2911.0,NaN,NaN,NaN,0.28066,0.895522,0.0,0.0,0.0,0.0,6.0
fan,2911.0,NaN,NaN,NaN,6.0,0.0,6.0,6.0,6.0,6.0,6.0
light,2911.0,NaN,NaN,NaN,10.0,0.0,10.0,10.0,10.0,10.0,10.0
wardrobe,2911.0,NaN,NaN,NaN,4.0,0.0,4.0,4.0,4.0,4.0,4.0
ac,2911.0,NaN,NaN,NaN,6.0,0.0,6.0,6.0,6.0,6.0,6.0
bed,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
chimney,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
curtains,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dining table,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
exhaust fan,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
geyser,2911.0,NaN,NaN,NaN,5.0,0.0,5.0,5.0,5.0,5.0,5.0
modular kitchen,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
microwave,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
fridge,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
sofa,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stove,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
tv,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
washing machine,2911.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
water purifier,2911.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
area_type,2911,3,super built up,1912,NaN,NaN,NaN,NaN,NaN,NaN,NaN
floor_rise,2911,3,high,1432,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,2911,4,new,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
society,2911,580,tulip violet,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,2911,3,gurgaon,2669,NaN,NaN,NaN,NaN,NaN,NaN,NaN