In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
pd.set_option('display.max_columns', None)

In [22]:
df = pd.read_csv('07_flats_EDA.csv')

In [23]:
df.head(2)

,price_cr,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,area_type,floor_rise,age,society,city
0,0.45,83.61,2,2,1,0,7,50,34,0,0,0,0,0,5,2,0,0,0,0,0,0,1,0,0,0,1,carpet,mid,new,maa bhagwati residency,gurgaon
1,0.50,60.39,2,2,1,0,3,48,4,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,carpet,low,old,apna enclave,gurgaon

In [24]:
X = df.iloc[:,1:]
y = df['price_cr']

In [25]:
X.head(3)

,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,area_type,floor_rise,age,society,city
0,83.61,2,2,1,0,7,50,34,0,0,0,0,0,5,2,0,0,0,0,0,0,1,0,0,0,1,carpet,mid,new,maa bhagwati residency,gurgaon
1,60.39,2,2,1,0,3,48,4,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,carpet,low,old,apna enclave,gurgaon
2,55.28,2,2,3,0,33,6,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,carpet,high,new,tulsiani easy in homes,sohna

In [26]:
y.head(3)

0    0.45
1    0.50
2    0.40
Name: price_cr, dtype: float64

In [27]:
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = pd.DataFrame(le.fit_transform(df[col]))

In [29]:
df.head()

,price_cr,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,area_type,floor_rise,age,society,city
0,0.45,83.61,2,2,1,0,7,50,34,0,0,0,0,0,5,2,0,0,0,0,0,0,1,0,0,0,1,1,2,1,284,0
1,0.50,60.39,2,2,1,0,3,48,4,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,1,1,2,48,0
2,0.40,55.28,2,2,3,0,33,6,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,1,531,2
3,1.47,111.48,2,2,2,1,61,9,1,0,0,1,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,1,1,0,458,0
4,0.70,124.95,2,2,3,1,92,11,4,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,1,2,2,3,339,0